export type Case = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly file?: string;
};

const TOO_LONG = "export const v = 1;\n".repeat(600);

export const CASES: readonly Case[] = [
  { rule: "TS-DEAD:3", name: "a named function that does nothing", expect: "fires",
    code: `export function save(o: number): void {}` },
  { rule: "TS-DEAD:3", name: "a no-op bound to a name is reachable by that name", expect: "fires",
    code: `export const noop = () => {};` },
  { rule: "TS-DEAD:3", name: "a method that does nothing", expect: "fires",
    code: `export class C { close(): void {} }` },
  { rule: "TS-DEAD:3", name: "an empty callback written inline is a decision, not an absence", expect: "silent",
    code: `export function wire(el: HTMLElement): void { el.addEventListener("click", () => {}); }` },
  { rule: "TS-DEAD:3", name: "yielding a tick is not a half-built function", expect: "silent",
    code: `export function later(): void { setTimeout(() => {}, 0); }` },
  { rule: "TS-DEAD:3", name: "an empty handler on a button is a decision written where it applies", expect: "silent",
    file: "src/Button.tsx",
    code: `export function Button(): JSX.Element { return <button onClick={() => {}}>x</button>; }` },
  { rule: "TS-ERROR:1", name: "a promise given a name and then abandoned", expect: "fires",
    file: "src/a.ts",
    code: `async function save(o: number): Promise<void> { await Promise.resolve(o); }\nexport function f(o: number): void { const p = save(o); }` },
  { rule: "TS-ERROR:1", name: "two started and both waited for is the shape the rule wants", expect: "silent",
    file: "src/a.ts",
    code: `async function save(o: number): Promise<void> { await Promise.resolve(o); }\nasync function mail(o: number): Promise<void> { await Promise.resolve(o); }\nexport async function f(o: number): Promise<void> { const saved = save(o); const mailed = mail(o); await Promise.all([saved, mailed]); }` },
  { rule: "TS-ERROR:1", name: "a named promise whose failure is handled is not abandoned", expect: "silent",
    file: "src/a.ts",
    code: `async function save(o: number): Promise<void> { await Promise.resolve(o); }\nexport function f(o: number, log: (e: unknown) => void): void { const p = save(o); p.catch(log); }` },
  { rule: "TS-TRUTH:1", name: "control: nullish default", expect: "fires",
    code: `const n = counts.get(k) ?? 0;` },
  { rule: "TS-TRUTH:1", name: "or as a default", expect: "fires",
    code: `const name = given || "anonymous";` },
  { rule: "TS-TRUTH:1", name: "nullish assignment", expect: "fires",
    code: `let n = counts.get(k);\nn ??= 0;` },
  { rule: "TS-TRUTH:1", name: "or assignment", expect: "fires",
    code: `let name = given;\nname ||= "anonymous";` },
  { rule: "TS-TRUTH:1", name: "a default parameter", expect: "fires",
    code: `export function page(size = 20): number { return size; }` },
  { rule: "TS-TRUTH:1", name: "a destructuring default", expect: "fires",
    code: `export function page({ size = 20 }): number { return size; }` },
  { rule: "TS-TRUTH:1", name: "the long-hand default", expect: "fires",
    code: `export function page(size: number): number { if (!size) size = 20; return size; }` },
  { rule: "TS-TRUTH:1", name: "a spread merge over defaults", expect: "fires",
    code: `const settings = { ...defaults, ...given };` },
  { rule: "TS-TRUTH:1", name: "or joining two comparisons is boolean logic", expect: "silent",
    code: `export function f(a: unknown, b: unknown): boolean { return a === b || (Array.isArray(a) && a.includes(b)); }` },
  { rule: "TS-TRUTH:1", name: "or joining two guards is boolean logic", expect: "silent",
    code: `export function f(v: unknown): boolean { return (v && v instanceof Set) || (isMap(v) && v.size > 0); }` },
  { rule: "TS-TRUTH:1", name: "or inside a condition is not a default", expect: "silent",
    code: `export function f(a: boolean, b: boolean): number { if (a || b) { return 1; } return 2; }` },
  { rule: "TS-TRUTH:1", name: "a guard is not a default", expect: "silent",
    code: `export function f(x: string | undefined): string { if (x === undefined) { throw new Missing(); } return x; }` },
  { rule: "TS-TRUTH:1", name: "naming the case is the compliant path", expect: "silent",
    code: `const held = counts.get(k);\nconst n = held === undefined ? 0 : held;` },
  { rule: "TS-TRUTH:1", name: "the sanctum may do it", expect: "silent", file: "src/config.ts",
    code: `export const port = fromEnv("PORT") ?? 8080;` },

  { rule: "TS-DECOMPOSITION:1", name: "control: a file past the cap", expect: "fires", code: TOO_LONG },
  { rule: "TS-DECOMPOSITION:1", name: "a short file is allowed", expect: "silent",
    code: `export const v = 1;` },

  { rule: "NEXT:1", name: "control: a private setting in a client file", expect: "fires", file: "page.tsx",
    code: `"use client";\nexport const key = process.env.STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "a public setting in a client file is allowed", expect: "silent", file: "page.tsx",
    code: `"use client";\nexport const style = process.env.NEXT_PUBLIC_MAP_STYLE;` },
  { rule: "NEXT:1", name: "a server file is not this rule's business", expect: "silent", file: "page.tsx",
    code: `export const key = process.env.STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "read by its name in brackets", expect: "fires", file: "page.tsx",
    code: `"use client";\nexport const key = process.env["STRIPE_SECRET"];` },
  { rule: "NEXT:1", name: "taken out of the settings by destructuring", expect: "fires", file: "page.tsx",
    code: `"use client";\nconst { STRIPE_SECRET } = process.env;\nexport const key = STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "every setting at once by destructuring the rest", expect: "fires", file: "page.tsx",
    code: `"use client";\nconst { NODE_ENV, ...rest } = process.env;\nexport const all = rest;` },
  { rule: "NEXT:1", name: "the settings given a shorter name first", expect: "fires", file: "page.tsx",
    code: `"use client";\nconst env = process.env;\nexport const key = env.STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "a public setting in brackets is still allowed", expect: "silent", file: "page.tsx",
    code: `"use client";\nexport const style = process.env["NEXT_PUBLIC_MAP_STYLE"];` },
  { rule: "NEXT:1", name: "a public setting destructured is still allowed", expect: "silent", file: "page.tsx",
    code: `"use client";\nconst { NEXT_PUBLIC_MAP_STYLE } = process.env;\nexport const style = NEXT_PUBLIC_MAP_STYLE;` },
  { rule: "NEXT:1", name: "a member read on something that is not the settings", expect: "silent", file: "page.tsx",
    code: `"use client";\nconst user = { STRIPE_SECRET: 1 };\nexport const key = user.STRIPE_SECRET;` },

  { rule: "TS-ERROR:1", name: "control: a promise nobody waits for", expect: "fires",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o); }` },
  { rule: "TS-ERROR:1", name: "awaited is allowed", expect: "silent",
    code: `async function save(o: number): Promise<void> {}\nexport async function f(o: number): Promise<void> { await save(o); }` },

  { rule: "TS-ERROR:7", name: "control: waiting work in a plain dispose", expect: "fires",
    code: `class C {\n  async close(): Promise<void> {}\n  [Symbol.dispose]() { this.close(); }\n}` },
  { rule: "TS-ERROR:7", name: "an async dispose is the right shape", expect: "silent",
    code: `class C {\n  async close(): Promise<void> {}\n  async [Symbol.asyncDispose]() { await this.close(); }\n}` },
  { rule: "TS-ERROR:8", name: "control: a missing bracket", expect: "fires",
    code: `export function f( {\n  return 1;\n` },
  { rule: "TS-ERROR:8", name: "a file that parses is left alone", expect: "silent",
    code: `export function f(): number { return 1; }` },
  { rule: "TS-ERROR:8", name: "a file that is not code at all", expect: "fires",
    code: `\u0000\u0001binary\u00ff\u00fe` },

  { rule: "TS-ERROR:3", name: "control: catch returns null", expect: "fires",
    code: `function f(){ try { g(); } catch { return null; } }` },
  { rule: "TS-ERROR:3", name: "launder through a variable", expect: "fires",
    code: `function f(){ try { g(); } catch { const fallback = null; return fallback; } }` },
  { rule: "TS-ERROR:3", name: "a failure reported as a value is allowed", expect: "silent",
    code: `async function send(): Promise<"ok" | "timed out" | "error"> { try { return "ok"; } catch (error) { if (error instanceof Error && error.name === "AbortError") { return "timed out"; } return "error"; } }` },
  { rule: "TS-ERROR:3", name: "the same answer the normal path gives is allowed", expect: "silent",
    code: `function supported(): boolean { try { if (typeof globalThis.localStorage !== "object") { return false; } return true; } catch (e) { return false; } }` },
  { rule: "TS-ERROR:3", name: "a value invented only for the failure still fires", expect: "fires",
    code: `function find(id: string) { try { return db.get(id); } catch { return null; } }` },
  { rule: "TS-ERROR:3", name: "a real value from the catch is allowed", expect: "silent",
    code: `function f(){ try { return g(); } catch (cause) { const fallback = recount(cause); return fallback; } }` },
  { rule: "TS-ERROR:3", name: "return NaN", expect: "fires",
    code: `function f(){ try { g(); } catch { return NaN; } }` },
  { rule: "TS-ERROR:3", name: "return void 0", expect: "fires",
    code: `function f(){ try { g(); } catch { return void 0; } }` },
  { rule: "TS-ERROR:3", name: "empty object behind an assertion", expect: "fires",
    code: `function f(): User { try { return g(); } catch { return {} as User; } }` },
  { rule: "TS-ERROR:3", name: "then's second argument", expect: "fires",
    code: `const p = g().then((x) => x, () => null);` },
  { rule: "TS-ERROR:3", name: "catch handler named elsewhere", expect: "fires",
    code: `const swallow = () => []; const p = g().catch(swallow);` },

  { rule: "TS-ERROR:4", name: "control: catch never reads it", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { return 1; } }` },
  { rule: "TS-ERROR:4", name: "mention it and throw it away", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { String(e); return 1; } }` },
  { rule: "TS-ERROR:4", name: "assign it to a bin", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { const _unused = e; return 1; } }` },
  { rule: "TS-ERROR:4", name: "name it and drop it", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { const detail = String(e); return 1; } }` },
  { rule: "TS-ERROR:4", name: "mention it in a template and drop that", expect: "fires",
    code: "function f(){ try { g(); } catch (e) { \`${e}\`; return 1; } }" },
  { rule: "TS-ERROR:4", name: "throwing it on is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { throw new Wrapped(e); } }` },
  { rule: "TS-ERROR:4", name: "a bare rethrow is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { throw e; } }` },
  { rule: "TS-ERROR:4", name: "returning it is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { return { kind: "bad", detail: String(e) }; } }` },
  { rule: "TS-ERROR:4", name: "named, then returned, is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { const detail = String(e); return { kind: "bad", detail }; } }` },
  { rule: "TS-ERROR:4", name: "rejecting a promise with it is allowed", expect: "silent",
    code: `function f(resolve, reject){ try { g(); } catch (e) { reject(e); } }` },
  { rule: "TS-ERROR:4", name: "handing it to a callback is allowed", expect: "silent",
    code: `function f(done){ try { g(); } catch (e) { done(e); } }` },
  { rule: "TS-ERROR:4", name: "putting it into state is allowed", expect: "silent",
    code: `function f(setState){ try { g(); } catch (e) { setState({ error: e }); } }` },
  { rule: "TS-ERROR:4", name: "examining it to decide the answer is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { if (e.name === "AbortError") return "timed out"; return "error"; } }` },
  { rule: "TS-ERROR:4", name: "keeping it in an outer variable is allowed", expect: "silent",
    code: `function f(){ let errors; try { g(); } catch (e) { errors = [e]; } return errors; }` },
  { rule: "TS-ERROR:4", name: "recovering after a rethrow test is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { if (e.code === "X") return null; throw e; } }` },

  { rule: "TS-TYPE:3", name: "control: as any", expect: "fires", code: `const a = x as any;` },
  { rule: "TS-TYPE:3", name: "control: as unknown as T", expect: "fires", code: `const a = x as unknown as User;` },
  { rule: "TS-TYPE:3", name: "as any as T", expect: "fires", code: `const a = x as any as User;` },
  { rule: "TS-TYPE:3", name: "an any variable is TS-TYPE:4's to catch, one line up", expect: "silent",
    code: `const loose: any = x; const a: User = loose;` },
  { rule: "TS-TYPE:3", name: "control: non-null bang", expect: "fires", code: `const a = x!.name;` },
  { rule: "TS-TYPE:3", name: "the angle-bracket assertion", expect: "fires", code: `const a = <User>x;` },

  { rule: "TS-TYPE:4", name: "control: any annotation", expect: "fires", code: `let a: any = 1;` },
  { rule: "TS-TYPE:4", name: "any behind a type alias", expect: "fires",
    code: `type Loose = any; let a: Loose = 1;` },
  { rule: "TS-TYPE:4", name: "any as a generic default", expect: "fires",
    code: `function f<T = any>(v: T): T { return v; }` },
  { rule: "TS-TYPE:4", name: "any inside Record", expect: "fires", code: `let a: Record<string, any> = {};` },

  { rule: "TS-DEAD:2", name: "control: an ordinary comment", expect: "fires", code: `// why\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "a triple-slash reference is an instruction, not prose", expect: "silent",
    code: `/// <reference path="./operators/index.ts" />\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "a licence header at the top is allowed", expect: "silent",
    code: `/*\n * Copyright (c) 2026 Someone\n * SPDX-License-Identifier: MIT\n */\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "prose lower down is not a licence header", expect: "fires",
    code: `const a = 1;\n/*\n * Copyright (c) 2026 Someone\n */\nconst b = 2;` },

  { rule: "TS-DEAD:1", name: "control: ts-ignore", expect: "fires", code: `// @ts-ignore\nconst a = 1;` },
  { rule: "TS-DEAD:1", name: "no space after slashes", expect: "fires", code: `//@ts-ignore\nconst a = 1;` },
  { rule: "TS-DEAD:1", name: "block form", expect: "fires", code: `/* @ts-ignore */\nconst a = 1;` },
  { rule: "TS-DEAD:1", name: "eslint-disable", expect: "fires", code: `/* eslint-disable no-eval */\nconst a = 1;` },

  { rule: "TS-TRUTH:2", name: "control: process.env", expect: "fires", code: `const a = process.env.TOKEN;` },
  { rule: "TS-TRUTH:2", name: "alias process", expect: "fires", code: `const p = process; const a = p.env.TOKEN;` },
  { rule: "TS-TRUTH:2", name: "computed member", expect: "fires", code: `const a = process["env"].TOKEN;` },
  { rule: "TS-TRUTH:2", name: "destructure env", expect: "fires", code: `const { env } = process; const a = env.TOKEN;` },
  { rule: "TS-TRUTH:2", name: "through globalThis", expect: "fires", code: `const a = globalThis.process.env.TOKEN;` },

  { rule: "TS-LOG:1", name: "control: console.log", expect: "fires", code: `console.log("hi");` },
  { rule: "TS-LOG:1", name: "alias console", expect: "fires", code: `const c = console; c.log("hi");` },
  { rule: "TS-LOG:1", name: "through globalThis", expect: "fires", code: `globalThis.console.log("hi");` },
  { rule: "TS-LOG:1", name: "destructure log", expect: "fires", code: `const { log } = console; log("hi");` },
  { rule: "TS-LOG:1", name: "stdout belongs to TS-LOG:2, which is not built (finding 26)", expect: "silent", code: `process.stdout.write("hi\\n");` },

  { rule: "TS-DEAD:4", name: "control: export star", expect: "fires", code: `export * from "./types";` },
  { rule: "TS-DEAD:4", name: "export star as namespace", expect: "fires", code: `export * as types from "./types";` },
  { rule: "TS-DEAD:4", name: "control: import star from own file", expect: "fires", code: `import * as t from "./types";` },
  { rule: "TS-DEAD:4", name: "third-party namespace is allowed", expect: "silent", code: `import * as path from "node:path";` },

  { rule: "TS-ERROR:6", name: "forEach an async function expression", expect: "fires",
    code: `items.forEach(async function (i) { await save(i); });` },
  { rule: "TS-ERROR:6", name: "control: forEach async arrow", expect: "fires",
    code: `items.forEach(async (i) => { await save(i); });` },
  { rule: "TS-ERROR:6", name: "forEach handing back a promise", expect: "fires",
    code: `async function save(i: number) { await write(i); }\nitems.forEach((i) => save(i));` },
  { rule: "TS-ERROR:6", name: "a plain handler is allowed", expect: "silent",
    code: `function tally(i: number) { total += i; }\nitems.forEach(tally);` },
  { rule: "TS-ERROR:6", name: "a map whose answer is used is allowed", expect: "silent",
    code: `const waiting = items.map(async (i) => { await save(i); });\nawait Promise.all(waiting);` },
  { rule: "TS-ERROR:6", name: "forEach with a named async handler", expect: "fires",
    code: `async function save(i: number) { await write(i); }\nitems.forEach(save);` },
  { rule: "TS-ERROR:6", name: "map with async, never awaited", expect: "fires",
    code: `items.map(async (i) => { await save(i); });` },

  { rule: "TS-LAYER:2", name: "control: require in a function", expect: "fires",
    code: `function f(){ const m = require("./m"); return m; }` },
  { rule: "TS-LAYER:2", name: "control: dynamic import in a function", expect: "fires",
    code: `async function f(){ const m = await import("./m"); return m; }` },
  { rule: "TS-LAYER:2", name: "alias require", expect: "fires",
    code: `const r = require; function f(){ return r("./m"); }` },
  { rule: "TS-LAYER:2", name: "createRequire", expect: "fires",
    code: `import { createRequire } from "node:module";\nfunction f(){ return createRequire(import.meta.url)("./m"); }` },

  { rule: "TS-TYPE:5", name: "control: parseInt no radix", expect: "fires", code: `const n = parseInt(s);` },
  { rule: "TS-TYPE:5", name: "Number.parseInt no radix", expect: "fires", code: `const n = Number.parseInt(s);` },
  { rule: "TS-TYPE:5", name: "control: double tilde", expect: "fires", code: `const n = ~~s;` },
  { rule: "TS-TYPE:5", name: "shift by zero", expect: "fires", code: `const n = s >> 0;` },
  { rule: "TS-TYPE:5", name: "parseInt with radix is allowed", expect: "silent", code: `const n = parseInt(s, 10);` },

  { rule: "TS-TYPE:2", name: "control: exported nullable return", expect: "fires",
    code: `export function f(): string | null { return null; }` },
  { rule: "TS-TYPE:2", name: "exported arrow const", expect: "fires",
    code: `export const f = (): string | null => null;` },
  { rule: "TS-TYPE:2", name: "nullable behind an alias", expect: "fires",
    code: `type Maybe = string | null;\nexport function f(): Maybe { return null; }` },
  { rule: "TS-TYPE:2", name: "export default", expect: "fires",
    code: `export default function f(): string | null { return null; }` },
  { rule: "TS-TYPE:2", name: "a declared function still promises what it promises", expect: "fires",
    code: `export declare function find(id: string): User | null;` },
  { rule: "TS-TYPE:4", name: "an enum is not any", expect: "silent",
    code: `export enum Colour { Red, Blue }` },
  { rule: "TS-TYPE:2", name: "wrapper generic is not a nullable return", expect: "silent",
    code: `export function f(): Box<string | null> { return box(); }` },

  { rule: "TS-DEAD:3", name: "control: empty exported function", expect: "fires",
    code: `export function f(): void {}` },
  { rule: "TS-DEAD:3", name: "bare return", expect: "fires",
    code: `export function f(): void { return; }` },
  { rule: "TS-DEAD:3", name: "control: not implemented", expect: "fires",
    code: `export function f(): void { throw new Error("not implemented"); }` },
  { rule: "TS-DEAD:3", name: "TODO instead of not implemented", expect: "fires",
    code: `export function f(): void { throw new Error("TODO"); }` },
  { rule: "TS-DEAD:3", name: "parameter property is not a stub", expect: "silent",
    code: `class A { constructor(private readonly x: number) {} }` },

  { rule: "DATA:1", name: "control: concatenated sql", expect: "fires",
    code: `const rows = db.query("SELECT * FROM users WHERE id = " + id);` },
  { rule: "DATA:1", name: "template literal sql", expect: "fires",
    code: "const rows = db.query(`SELECT * FROM users WHERE id = ${id}`);" },
  { rule: "DATA:1", name: "built one line earlier", expect: "fires",
    code: `const q = "SELECT * FROM users WHERE id = " + id;\nconst rows = db.query(q);` },
  { rule: "DATA:1", name: "built two lines earlier", expect: "fires",
    code: `const base = "SELECT * FROM users WHERE id = " + id;\nconst q = base;\nconst rows = db.query(q);` },
  { rule: "DATA:1", name: "parameters are allowed", expect: "silent",
    code: `const rows = db.query("SELECT * FROM users WHERE id = $1", [id]);` },
  { rule: "DATA:1", name: "a built string that is not sql is allowed", expect: "silent",
    code: "const label = `user ${id}`;\nconst rows = db.query(label);" },

  { rule: "NODE:1", name: "control: exec with concatenation", expect: "fires",
    code: `import { exec } from "node:child_process";\nexec("ls " + dir);` },
  { rule: "NODE:1", name: "template literal command", expect: "fires",
    code: "import { exec } from \"node:child_process\";\nexec(`ls ${dir}`);" },
  { rule: "NODE:1", name: "built one line earlier", expect: "fires",
    code: `import { execSync } from "node:child_process";\nconst cmd = "ls " + dir;\nexecSync(cmd);` },
  { rule: "NODE:1", name: "spawn with a shell", expect: "fires",
    code: "import { spawn } from \"node:child_process\";\nspawn(`ls ${dir}`, { shell: true });" },
  { rule: "NODE:1", name: "arguments kept as arguments is allowed", expect: "silent",
    code: `import { spawn } from "node:child_process";\nspawn("git", ["clone", url]);` },
  { rule: "NODE:1", name: "execFile with an array is allowed", expect: "silent",
    code: `import { execFile } from "node:child_process";\nexecFile("convert", [input, output]);` },
  { rule: "NODE:1", name: "a built string that never reaches a shell is allowed", expect: "silent",
    code: "const greeting = `hello ${name}`;\nlogger.info(greeting);" },

  { rule: "DATA:2", name: "control: const from response.json", expect: "fires",
    code: `async function f(){ const body = await response.json(); return body.id; }` },
  { rule: "DATA:2", name: "assigned to an existing variable", expect: "fires",
    code: `async function f(){ let body; body = await response.json(); return body.id; }` },
  { rule: "DATA:2", name: "returned straight out", expect: "fires",
    code: `async function f(){ return await response.json(); }` },
  { rule: "DATA:2", name: "request body in a handler", expect: "fires",
    code: `async function f(req){ const body = await req.json(); return body.id; }` },
  { rule: "DATA:2", name: "destructured on arrival", expect: "fires",
    code: `async function f(req){ const { id } = await req.json(); return id; }` },
  { rule: "DATA:2", name: "passed straight to something else", expect: "fires",
    code: `async function f(req){ return save(await req.json()); }` },
  { rule: "DATA:2", name: "assigned onto a property", expect: "fires",
    code: `async function f(req){ this.body = await req.json(); }` },
  { rule: "DATA:2", name: "form data, not json", expect: "fires",
    code: `async function f(req){ const body = await req.formData(); return body.get("id"); }` },
  { rule: "DATA:2", name: "drained and thrown away is allowed", expect: "silent",
    code: `async function f(res){ await res.text(); return retry(); }` },
  { rule: "DATA:2", name: "checked on the spot is allowed", expect: "silent",
    code: `async function f(req){ const order = OrderSchema.parse(await req.json()); return order; }` },
  { rule: "DATA:2", name: "checked one line later is allowed", expect: "silent",
    code: `async function f(req){ const body = await req.json(); const order = OrderSchema.parse(body); return order; }` },
  { rule: "DATA:2", name: "safeParse is allowed", expect: "silent",
    code: `async function f(req){ const body = await req.json(); const r = OrderSchema.safeParse(body); return r; }` },
  { rule: "DATA:2", name: "checked on the spot, then returned", expect: "silent",
    code: `async function f(req){ return OrderSchema.parse(await req.json()); }` },

  { rule: "REACT:1", name: "control: hook inside an if", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { if (on) { const [a] = useState(0); } return null; }` },
  { rule: "REACT:1", name: "hook behind a logical and", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { on && useState(0); return null; }` },
  { rule: "REACT:1", name: "hook in a ternary", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { const a = on ? useState(0) : null; return null; }` },
  { rule: "REACT:1", name: "hook after an early return", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { if (!on) return null; const [a] = useState(0); return null; }` },
  { rule: "REACT:1", name: "hook after a braced early return", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { if (!on) { return null; } useState(0); return null; }` },
  { rule: "REACT:1", name: "a return at the end is not early", expect: "silent", file: "C.tsx",
    code: `function C() { useState(0); return null; }` },
  { rule: "REACT:1", name: "a return inside an effect is not the component's", expect: "silent", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { if (!id) return; load(id); }, [id]); return null; }` },
  { rule: "REACT:1", name: "hook inside a do-while", expect: "fires", file: "C.tsx",
    code: `function C({ n }) { do { useState(n); } while (n > 0); return null; }` },
  { rule: "REACT:1", name: "hook inside a for-in", expect: "fires", file: "C.tsx",
    code: `function C({ o }) { for (const k in o) { useState(k); } return null; }` },
  { rule: "REACT:1", name: "hook inside a switch", expect: "fires", file: "C.tsx",
    code: `function C({ k }) { switch (k) { case 1: useState(0); } return null; }` },
  { rule: "REACT:1", name: "hook inside a loop", expect: "fires", file: "C.tsx",
    code: `function C({ items }) { for (const i of items) { useState(i); } return null; }` },

  { rule: "REACT:2", name: "control: missing dependency", expect: "fires", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { load(id); }, []); return null; }` },
  { rule: "REACT:2", name: "missing a member dependency", expect: "fires", file: "C.tsx",
    code: `function C({ user }) { useEffect(() => { load(user.id); }, []); return null; }` },
  { rule: "REACT:2", name: "missing a prop reached through props", expect: "fires", file: "C.tsx",
    code: `function C(props) { useEffect(() => { load(props.id); }, []); return null; }` },
  { rule: "REACT:2", name: "missing a useState value", expect: "fires", file: "C.tsx",
    code: `function C() { const [id, setId] = useState(0); useEffect(() => { load(id); }, []); return null; }` },
  { rule: "REACT:2", name: "a field name that matches nothing is not a dependency", expect: "silent", file: "C.tsx",
    code: `function C({ user }) { const id = 1; useEffect(() => { send(user.id); }, [user]); return null; }` },
  { rule: "REACT:2", name: "declared inside the effect is allowed", expect: "silent", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { const n = id + 1; log(n); }, [id]); return null; }` },
  { rule: "REACT:2", name: "complete list is allowed", expect: "silent", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { load(id); }, [id]); return null; }` },
];
