export type Case = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly file?: string;
};

const TOO_LONG = "export const v = 1;\n".repeat(600);

export const CASES: readonly Case[] = [
  { rule: "TS-DEAD:3", name: "a named function that does nothing", expect: "fires",
    code: `export function save(o: number): void {}` },
  { rule: "TS-DEAD:3", name: "a no-op bound to a name is reachable by that name", expect: "fires",
    code: `export const noop = () => {};` },
  { rule: "TS-DEAD:3", name: "a method that does nothing", expect: "fires",
    code: `export class C { close(): void {} }` },
  { rule: "TS-DEAD:3", name: "an empty callback written inline is a decision, not an absence", expect: "silent",
    code: `export function wire(el: HTMLElement): void { el.addEventListener("click", () => {}); }` },
  { rule: "TS-DEAD:3", name: "yielding a tick is not a half-built function", expect: "silent",
    code: `export function later(): void { setTimeout(() => {}, 0); }` },
  { rule: "TS-DEAD:3", name: "an empty handler on a button is a decision written where it applies", expect: "silent",
    file: "src/Button.tsx",
    code: `export function Button(): JSX.Element { return <button onClick={() => {}}>x</button>; }` },
  { rule: "TS-ERROR:1", name: "a promise given a name and then abandoned", expect: "fires",
    file: "src/a.ts",
    code: `async function save(o: number): Promise<void> { await Promise.resolve(o); }\nexport function f(o: number): void { const p = save(o); }` },
  { rule: "TS-ERROR:1", name: "two started and both waited for is the shape the rule wants", expect: "silent",
    file: "src/a.ts",
    code: `async function save(o: number): Promise<void> { await Promise.resolve(o); }\nasync function mail(o: number): Promise<void> { await Promise.resolve(o); }\nexport async function f(o: number): Promise<void> { const saved = save(o); const mailed = mail(o); await Promise.all([saved, mailed]); }` },
  { rule: "TS-ERROR:1", name: "a named promise whose failure is handled is not abandoned", expect: "silent",
    file: "src/a.ts",
    code: `async function save(o: number): Promise<void> { await Promise.resolve(o); }\nexport function f(o: number, log: (e: unknown) => void): void { const p = save(o); p.catch(log); }` },
  { rule: "TS-TRUTH:1", name: "control: nullish default", expect: "fires",
    code: `const n = counts.get(k) ?? 0;` },
  { rule: "TS-TRUTH:1", name: "or as a default", expect: "fires",
    code: `const name = given || "anonymous";` },
  { rule: "TS-TRUTH:1", name: "nullish assignment", expect: "fires",
    code: `let n = counts.get(k);\nn ??= 0;` },
  { rule: "TS-TRUTH:1", name: "or assignment", expect: "fires",
    code: `let name = given;\nname ||= "anonymous";` },
  { rule: "TS-TRUTH:1", name: "a default parameter", expect: "fires",
    code: `export function page(size = 20): number { return size; }` },
  { rule: "TS-TRUTH:1", name: "a destructuring default", expect: "fires",
    code: `export function page({ size = 20 }): number { return size; }` },
  { rule: "TS-TRUTH:1", name: "the long-hand default", expect: "fires",
    code: `export function page(size: number): number { if (!size) size = 20; return size; }` },
  { rule: "TS-TRUTH:1", name: "a spread merge over a literal is still defaults", expect: "fires",
    code: `const held = { ...{ retries: 3 }, ...given };` },
  { rule: "TS-TRUTH:1", name: "copying a parameter and patching it fires too, which is wider than the harm", expect: "fires",
    code: `export function patched(current: Draft, patch: Partial<Draft>): Draft {\n  return { ...current, ...patch };\n}` },
  { rule: "TS-TRUTH:1", name: "copying a local and patching it fires too, for the same reason", expect: "fires",
    code: `export function patched(map: Record<string, Draft>, code: string, patch: Partial<Draft>) {\n  const held = map[code];\n  if (held === undefined) throw new Missing(code);\n  return { ...held, ...patch };\n}` },
  { rule: "TS-TRUTH:1", name: "one spread and a replaced key is not two spreads, so it is silent", expect: "silent",
    code: `export function withOne(map: Record<string, Draft>, code: string, next: Draft) {\n  return { ...map, [code]: next };\n}` },
  { rule: "TS-TRUTH:1", name: "a spread merge over defaults", expect: "fires",
    code: `const settings = { ...defaults, ...given };` },
  { rule: "TS-TRUTH:1", name: "or joining two comparisons is boolean logic", expect: "silent",
    code: `export function f(a: unknown, b: unknown): boolean { return a === b || (Array.isArray(a) && a.includes(b)); }` },
  { rule: "TS-TRUTH:1", name: "or joining two guards is boolean logic", expect: "silent",
    code: `export function f(v: unknown): boolean { return (v && v instanceof Set) || (isMap(v) && v.size > 0); }` },
  { rule: "TS-TRUTH:1", name: "or inside a condition is not a default", expect: "silent",
    code: `export function f(a: boolean, b: boolean): number { if (a || b) { return 1; } return 2; }` },
  { rule: "TS-TRUTH:1", name: "a guard is not a default", expect: "silent",
    code: `export function f(x: string | undefined): string { if (x === undefined) { throw new Missing(); } return x; }` },
  { rule: "TS-TRUTH:1", name: "naming the case is the compliant path", expect: "silent",
    code: `const held = counts.get(k);\nconst n = held === undefined ? 0 : held;` },
  { rule: "TS-TRUTH:1", name: "the sanctum may do it", expect: "silent", file: "src/config.ts",
    code: `export const port = fromEnv("PORT") ?? 8080;` },

  { rule: "TS-DECOMPOSITION:1", name: "control: a file past the cap", expect: "fires", code: TOO_LONG },
  { rule: "TS-DECOMPOSITION:1", name: "a short file is allowed", expect: "silent",
    code: `export const v = 1;` },

  { rule: "NEXT:1", name: "control: a private setting in a client file", expect: "fires", file: "page.tsx",
    code: `"use client";\nexport const key = process.env.STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "a public setting in a client file is allowed", expect: "silent", file: "page.tsx",
    code: `"use client";\nexport const style = process.env.NEXT_PUBLIC_MAP_STYLE;` },
  { rule: "NEXT:1", name: "a server file is not this rule's business", expect: "silent", file: "page.tsx",
    code: `export const key = process.env.STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "read by its name in brackets", expect: "fires", file: "page.tsx",
    code: `"use client";\nexport const key = process.env["STRIPE_SECRET"];` },
  { rule: "NEXT:1", name: "taken out of the settings by destructuring", expect: "fires", file: "page.tsx",
    code: `"use client";\nconst { STRIPE_SECRET } = process.env;\nexport const key = STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "every setting at once by destructuring the rest", expect: "fires", file: "page.tsx",
    code: `"use client";\nconst { NODE_ENV, ...rest } = process.env;\nexport const all = rest;` },
  { rule: "NEXT:1", name: "the settings given a shorter name first", expect: "fires", file: "page.tsx",
    code: `"use client";\nconst env = process.env;\nexport const key = env.STRIPE_SECRET;` },
  { rule: "NEXT:1", name: "a public setting in brackets is still allowed", expect: "silent", file: "page.tsx",
    code: `"use client";\nexport const style = process.env["NEXT_PUBLIC_MAP_STYLE"];` },
  { rule: "NEXT:1", name: "a public setting destructured is still allowed", expect: "silent", file: "page.tsx",
    code: `"use client";\nconst { NEXT_PUBLIC_MAP_STYLE } = process.env;\nexport const style = NEXT_PUBLIC_MAP_STYLE;` },
  { rule: "NEXT:1", name: "a member read on something that is not the settings", expect: "silent", file: "page.tsx",
    code: `"use client";\nconst user = { STRIPE_SECRET: 1 };\nexport const key = user.STRIPE_SECRET;` },

  { rule: "TS-ERROR:1", name: "control: a promise nobody waits for", expect: "fires",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o); }` },
  { rule: "TS-ERROR:1", name: "awaited is allowed", expect: "silent",
    code: `async function save(o: number): Promise<void> {}\nexport async function f(o: number): Promise<void> { await save(o); }` },
  { rule: "TS-ERROR:1", name: "discarded with void", expect: "fires",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { void save(o); }` },
  { rule: "TS-ERROR:1", name: "then with nothing for the failure", expect: "fires",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o).then(() => {}); }` },
  { rule: "TS-ERROR:1", name: "then with only a success handler, chained", expect: "fires",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o).then(() => {}).finally(() => {}); }` },
  { rule: "TS-ERROR:1", name: "the repair the rule prescribes is allowed", expect: "silent",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o).catch((cause) => logger.error({ cause })); }` },
  { rule: "TS-ERROR:1", name: "then with a failure handler beside it is allowed", expect: "silent",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o).then(() => {}, (cause) => logger.error({ cause })); }` },
  { rule: "TS-ERROR:1", name: "a chain that ends in catch is allowed", expect: "silent",
    code: `async function save(o: number): Promise<void> {}\nexport function f(o: number): void { save(o).then(() => {}).catch((cause) => logger.error({ cause })); }` },

  { rule: "TS-ERROR:7", name: "control: waiting work in a plain dispose", expect: "fires",
    code: `class C {\n  async close(): Promise<void> {}\n  [Symbol.dispose]() { this.close(); }\n}` },
  { rule: "TS-ERROR:7", name: "an async dispose is the right shape", expect: "silent",
    code: `class C {\n  async close(): Promise<void> {}\n  async [Symbol.asyncDispose]() { await this.close(); }\n}` },
  { rule: "TS-ERROR:8", name: "control: a missing bracket", expect: "fires",
    code: `export function f( {\n  return 1;\n` },
  { rule: "TS-ERROR:8", name: "a file that parses is left alone", expect: "silent",
    code: `export function f(): number { return 1; }` },
  { rule: "TS-ERROR:8", name: "a file that is not code at all", expect: "fires",
    code: `\u0000\u0001binary\u00ff\u00fe` },
  { rule: "TS-ERROR:8", name: "a decorator on a constructor argument is how dependency injection is spelled", expect: "silent",
    code: `export class Cleaner { constructor(@ILogService private readonly log: ILogService) {} }` },
  { rule: "TS-ERROR:8", name: "a decorator on a method argument", expect: "silent",
    code: `export class Route { go(@Body() body: Payload): void {} }` },
  { rule: "TS-ERROR:8", name: "a decorated argument beside an undecorated one", expect: "silent",
    code: `export class Cleaner { constructor(path: string | undefined, @IProductService product: IProductService) {} }` },
  { rule: "TS-ERROR:8", name: "a decorated auto-accessor", expect: "silent",
    code: `export class Counter { @observable accessor count = 0; }` },
  { rule: "TS-ERROR:8", name: "a decorated private auto-accessor", expect: "silent",
    code: `export class Counter { @observable accessor #count = 0; }` },
  { rule: "TS-ERROR:8", name: "an auto-accessor with no decorator at all", expect: "silent",
    code: `export class Counter { accessor count = 0; }` },
  { rule: "TS-ERROR:8", name: "an abstract class carrying decorators", expect: "silent",
    code: `@Injectable() export abstract class Base { @Input() abstract go(): void; }` },
  { rule: "TS-ERROR:8", name: "a decorator that is a call chain", expect: "silent",
    code: `@factory.for("widget")() export class Widget {}` },
  { rule: "TS-ERROR:8", name: "a decorator written after export, which the newer proposal allows", expect: "silent",
    code: `export @Component({ selector: "app" }) class Widget {}` },
  { rule: "TS-ERROR:8", name: "a decorated argument in a file that also holds jsx", expect: "silent",
    file: "src/Widget.tsx",
    code: `export class Widget { constructor(@Inject(TOKEN) private readonly dep: Dep) {} }\nexport function View(): JSX.Element { return <div />; }` },

  { rule: "TS-ERROR:3", name: "control: catch returns null", expect: "fires",
    code: `function f(){ try { g(); } catch { return null; } }` },
  { rule: "TS-ERROR:3", name: "launder through a variable", expect: "fires",
    code: `function f(){ try { g(); } catch { const fallback = null; return fallback; } }` },
  { rule: "TS-ERROR:3", name: "a failure reported as a value is allowed", expect: "silent",
    code: `async function send(): Promise<"ok" | "timed out" | "error"> { try { return "ok"; } catch (error) { if (error instanceof Error && error.name === "AbortError") { return "timed out"; } return "error"; } }` },
  { rule: "TS-ERROR:3", name: "the same answer the normal path gives is allowed", expect: "silent",
    code: `function supported(): boolean { try { if (typeof globalThis.localStorage !== "object") { return false; } return true; } catch (e) { return false; } }` },
  { rule: "TS-ERROR:3", name: "a default returned before the try is still the handler's own", expect: "fires",
    code: `function toNumber(v): number { if (v === null) { return 0; } try { return Number(v); } catch (e) { return 0; } }` },
  { rule: "TS-ERROR:3", name: "a value invented only for the failure still fires", expect: "fires",
    code: `function find(id: string) { try { return db.get(id); } catch { return null; } }` },
  { rule: "TS-ERROR:3", name: "the made-up value kept outside the catch", expect: "fires",
    code: `const NONE: readonly number[] = [];\nexport function f(){ try { return g(); } catch { return NONE; } }` },
  { rule: "TS-ERROR:3", name: "the made-up value kept beside the function", expect: "fires",
    code: `const MISSING = null;\nexport function find(id: string){ try { return db.get(id); } catch { return MISSING; } }` },
  { rule: "TS-ERROR:3", name: "an outside value the normal path also returns is allowed", expect: "silent",
    code: `const NONE: readonly number[] = [];\nexport function f(){ try { if (!ready) { return NONE; } return g(); } catch { return NONE; } }` },
  { rule: "TS-ERROR:3", name: "a real value from outside is allowed", expect: "silent",
    code: `const fallback = recount();\nexport function f(){ try { return g(); } catch { return fallback; } }` },
  { rule: "TS-ERROR:3", name: "a real value from the catch is allowed", expect: "silent",
    code: `function f(){ try { return g(); } catch (cause) { const fallback = recount(cause); return fallback; } }` },
  { rule: "TS-ERROR:3", name: "return NaN", expect: "fires",
    code: `function f(){ try { g(); } catch { return NaN; } }` },
  { rule: "TS-ERROR:3", name: "return void 0", expect: "fires",
    code: `function f(){ try { g(); } catch { return void 0; } }` },
  { rule: "TS-ERROR:3", name: "empty object behind an assertion", expect: "fires",
    code: `function f(): User { try { return g(); } catch { return {} as User; } }` },
  { rule: "TS-ERROR:3", name: "then's second argument", expect: "fires",
    code: `const p = g().then((x) => x, () => null);` },
  { rule: "TS-ERROR:3", name: "catch handler named elsewhere", expect: "fires",
    code: `const swallow = () => []; const p = g().catch(swallow);` },

  { rule: "TS-ERROR:4", name: "control: catch never reads it", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { return 1; } }` },
  { rule: "TS-ERROR:4", name: "mention it and throw it away", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { String(e); return 1; } }` },
  { rule: "TS-ERROR:4", name: "assign it to a bin", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { const _unused = e; return 1; } }` },
  { rule: "TS-ERROR:4", name: "name it and drop it", expect: "fires",
    code: `function f(){ try { g(); } catch (e) { const detail = String(e); return 1; } }` },
  { rule: "TS-ERROR:4", name: "mention it in a template and drop that", expect: "fires",
    code: "function f(){ try { g(); } catch (e) { \`${e}\`; return 1; } }" },
  { rule: "TS-ERROR:4", name: "throwing it on is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { throw new Wrapped(e); } }` },
  { rule: "TS-ERROR:4", name: "a bare rethrow is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { throw e; } }` },
  { rule: "TS-ERROR:4", name: "returning it is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { return { kind: "bad", detail: String(e) }; } }` },
  { rule: "TS-ERROR:4", name: "named, then returned, is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { const detail = String(e); return { kind: "bad", detail }; } }` },
  { rule: "TS-ERROR:4", name: "rejecting a promise with it is allowed", expect: "silent",
    code: `function f(resolve, reject){ try { g(); } catch (e) { reject(e); } }` },
  { rule: "TS-ERROR:4", name: "handing it to a callback is allowed", expect: "silent",
    code: `function f(done){ try { g(); } catch (e) { done(e); } }` },
  { rule: "TS-ERROR:4", name: "putting it into state is allowed", expect: "silent",
    code: `function f(setState){ try { g(); } catch (e) { setState({ error: e }); } }` },
  { rule: "TS-ERROR:4", name: "examining it to decide the answer is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { if (e.name === "AbortError") return "timed out"; return "error"; } }` },
  { rule: "TS-ERROR:4", name: "keeping it in an outer variable is allowed", expect: "silent",
    code: `function f(){ let errors; try { g(); } catch (e) { errors = [e]; } return errors; }` },
  { rule: "TS-ERROR:4", name: "recovering after a rethrow test is allowed", expect: "silent",
    code: `function f(){ try { g(); } catch (e) { if (e.code === "X") return null; throw e; } }` },

  { rule: "TS-ERROR:4", name: "the doctrine's own spelling of the deleted failure", expect: "fires",
    code: `function f(){ work().catch(() => {}); }` },
  { rule: "TS-ERROR:4", name: "an empty handler with whitespace in it is the same handler", expect: "fires",
    code: `function f(){ work().catch(() => {  }); }` },
  { rule: "TS-ERROR:4", name: "a handler that only makes up a value belongs to TS-ERROR:3, which already has it", expect: "silent",
    code: `function f(){ return work().catch(() => 0); }` },
  { rule: "TS-ERROR:4", name: "the same boundary for null", expect: "silent",
    code: `function f(){ return work().catch(() => null); }` },
  { rule: "TS-ERROR:4", name: "a handler that calls something without ever looking at the failure", expect: "fires",
    code: `function f(){ work().catch(() => giveUp()); }` },
  { rule: "TS-ERROR:4", name: "naming it in the handler and dropping it", expect: "fires",
    code: `function f(){ work().catch((cause) => { const _unused = cause; }); }` },
  { rule: "TS-ERROR:4", name: "the same handler at the end of a chain", expect: "fires",
    code: `function f(){ work().then(() => {}).catch(() => {}); }` },
  { rule: "TS-ERROR:4", name: "the function-expression handler is the same handler", expect: "fires",
    code: `function f(){ work().catch(function (cause) { giveUp(); }); }` },
  { rule: "TS-ERROR:4", name: "throwing it on from the handler is allowed", expect: "silent",
    code: `function f(){ return work().catch((cause) => { throw new Wrapped(cause); }); }` },
  { rule: "TS-ERROR:4", name: "returning it from the handler is allowed", expect: "silent",
    code: `function f(){ return work().catch((cause) => ({ kind: "bad", detail: String(cause) })); }` },
  { rule: "TS-ERROR:4", name: "handing it to something else is allowed", expect: "silent",
    code: `function f(setError){ work().catch((cause) => { setError(cause); }); }` },
  { rule: "TS-ERROR:4", name: "a handler that is a name cannot be read here, so it is not judged", expect: "silent",
    code: `function f(handleIt){ work().catch(handleIt); }` },
  { rule: "TS-ERROR:3", name: "a handler that answers the failure with a number", expect: "fires",
    code: `function f(){ return work().catch(() => 0); }` },
  { rule: "TS-ERROR:3", name: "a handler that answers the failure with null", expect: "fires",
    code: `function f(){ return work().catch(() => null); }` },
  { rule: "TS-ERROR:4", name: "examining it to decide the answer is allowed in a handler too", expect: "silent",
    code: `function f(){ return work().catch((cause) => { if (cause.name === "AbortError") return "timed out"; throw cause; }); }` },

  { rule: "TS-TYPE:3", name: "control: as any", expect: "fires", code: `const a = x as any;` },
  { rule: "TS-TYPE:3", name: "control: as unknown as T", expect: "fires", code: `const a = x as unknown as User;` },
  { rule: "TS-TYPE:3", name: "as any as T", expect: "fires", code: `const a = x as any as User;` },
  { rule: "TS-TYPE:3", name: "an any variable is TS-TYPE:4's to catch, one line up", expect: "silent",
    code: `const loose: any = x; const a: User = loose;` },
  { rule: "TS-TYPE:3", name: "a plain cast to a named type is the same claim", expect: "fires",
    code: `const user = input as User;` },
  { rule: "TS-TYPE:3", name: "a plain cast to a builtin is still a claim", expect: "fires",
    code: `const name = held as string;` },
  { rule: "TS-TYPE:3", name: "as const asks for narrowing, it does not claim a type", expect: "silent",
    code: `const ports = [80, 443] as const;` },
  { rule: "TS-TYPE:3", name: "an import renamed with as is not a cast", expect: "silent",
    code: `import { CHECKS as EVERY_RULE } from "./checks.ts";\nexport const a = EVERY_RULE;` },
  { rule: "TS-TYPE:3", name: "an export renamed with as is not a cast", expect: "silent",
    code: `const one = 1;\nexport { one as first };` },
  { rule: "TS-TYPE:3", name: "satisfies checks instead of claiming, so it stays silent", expect: "silent",
    code: `type Config = { port: number };\nexport const config = { port: 8080 } satisfies Config;` },
  { rule: "TS-TYPE:3", name: "a type guard is the legal spelling and is not a cast", expect: "silent",
    code: `function isUser(value: unknown): value is { name: string } {\n  return typeof value === "object";\n}\nexport const check = isUser;` },
  { rule: "TS-TYPE:3", name: "control: non-null bang", expect: "fires", code: `const a = x!.name;` },
  { rule: "TS-TYPE:3", name: "the angle-bracket assertion", expect: "fires", code: `const a = <User>x;` },

  { rule: "TS-TYPE:4", name: "control: any annotation", expect: "fires", code: `let a: any = 1;` },
  { rule: "TS-TYPE:4", name: "any behind a type alias", expect: "fires",
    code: `type Loose = any; let a: Loose = 1;` },
  { rule: "TS-TYPE:4", name: "any as a generic default", expect: "fires",
    code: `function f<T = any>(v: T): T { return v; }` },
  { rule: "TS-TYPE:4", name: "any inside Record", expect: "fires", code: `let a: Record<string, any> = {};` },

  { rule: "TS-DEAD:2", name: "control: an ordinary comment", expect: "fires", code: `// why\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "a triple-slash reference is an instruction, not prose", expect: "silent",
    code: `/// <reference path="./operators/index.ts" />\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "looper's own allowance marker is read by looper, so it cannot go stale", expect: "silent",
    code: `const key = "AKIA0000111122223333"; // looper:allow-secret\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "the marker alone on a line does nothing for the gate, so it is prose", expect: "fires",
    code: `// looper:allow-secret\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "prose that merely mentions the marker is still prose", expect: "fires",
    code: `const a = 1; // we could put looper:allow-secret here one day` },
  { rule: "TS-DEAD:2", name: "the marker in a block comment is not the marker", expect: "fires",
    code: `const a = 1; /* looper:allow-secret */` },
  { rule: "TS-DEAD:2", name: "a licence header at the top is allowed", expect: "silent",
    code: `/*\n * Copyright (c) 2026 Someone\n * SPDX-License-Identifier: MIT\n */\nconst a = 1;` },
  { rule: "TS-DEAD:2", name: "prose lower down is not a licence header", expect: "fires",
    code: `const a = 1;\n/*\n * Copyright (c) 2026 Someone\n */\nconst b = 2;` },

  { rule: "TS-DEAD:1", name: "control: ts-ignore", expect: "fires", code: `// @ts-ignore\nconst a = 1;` },
  { rule: "TS-DEAD:1", name: "no space after slashes", expect: "fires", code: `//@ts-ignore\nconst a = 1;` },
  { rule: "TS-DEAD:1", name: "block form", expect: "fires", code: `/* @ts-ignore */\nconst a = 1;` },
  { rule: "TS-DEAD:1", name: "eslint-disable", expect: "fires", code: `/* eslint-disable no-eval */\nconst a = 1;` },

  { rule: "TS-TRUTH:2", name: "control: process.env", expect: "fires", code: `const a = process.env.TOKEN;` },
  { rule: "TS-TRUTH:2", name: "alias process", expect: "fires", code: `const p = process; const a = p.env.TOKEN;` },
  { rule: "TS-TRUTH:2", name: "computed member", expect: "fires", code: `const a = process["env"].TOKEN;` },
  { rule: "TS-TRUTH:2", name: "destructure env", expect: "fires", code: `const { env } = process; const a = env.TOKEN;` },
  { rule: "TS-TRUTH:2", name: "through globalThis", expect: "fires", code: `const a = globalThis.process.env.TOKEN;` },

  { rule: "TS-LOG:1", name: "control: console.log", expect: "fires", code: `console.log("hi");` },
  { rule: "TS-LOG:1", name: "alias console", expect: "fires", code: `const c = console; c.log("hi");` },
  { rule: "TS-LOG:1", name: "through globalThis", expect: "fires", code: `globalThis.console.log("hi");` },
  { rule: "TS-LOG:1", name: "destructure log", expect: "fires", code: `const { log } = console; log("hi");` },
  { rule: "TS-LOG:1", name: "stdout belongs to TS-LOG:2, which is not built (finding 26)", expect: "silent", code: `process.stdout.write("hi\\n");` },

  { rule: "TS-LOG:3", name: "control: template literal into a logger", expect: "fires",
    code: `import pino from "pino"; const log = pino(); log.info(\`saved \${id}\`);` },
  { rule: "TS-LOG:3", name: "concatenation is the same offence", expect: "fires",
    code: `import pino from "pino"; const log = pino(); log.warn("saved " + id);` },
  { rule: "TS-LOG:3", name: "a field beside a constant message is the shape that works", expect: "silent",
    code: `import pino from "pino"; const log = pino(); log.info({ order: id }, "saved");` },
  { rule: "TS-LOG:3", name: "a template literal with nothing in it is a string", expect: "silent",
    code: `import pino from "pino"; const log = pino(); log.info(\`saved\`);` },
  { rule: "TS-LOG:3", name: "no logger imported, so nothing here is a log line", expect: "silent",
    code: `const report = { info: (s: string) => s }; report.info(\`saved \${id}\`);` },

  { rule: "TS-DEAD:4", name: "control: export star", expect: "fires", code: `export * from "./types";` },
  { rule: "TS-DEAD:4", name: "export star as namespace", expect: "fires", code: `export * as types from "./types";` },
  { rule: "TS-DEAD:4", name: "control: import star from own file", expect: "fires", code: `import * as t from "./types";` },
  { rule: "TS-DEAD:4", name: "third-party namespace is allowed", expect: "silent", code: `import * as path from "node:path";` },

  { rule: "TS-ERROR:6", name: "forEach an async function expression", expect: "fires",
    code: `items.forEach(async function (i) { await save(i); });` },
  { rule: "TS-ERROR:6", name: "control: forEach async arrow", expect: "fires",
    code: `items.forEach(async (i) => { await save(i); });` },
  { rule: "TS-ERROR:6", name: "forEach handing back a promise", expect: "fires",
    code: `async function save(i: number) { await write(i); }\nitems.forEach((i) => save(i));` },
  { rule: "TS-ERROR:6", name: "a plain handler is allowed", expect: "silent",
    code: `function tally(i: number) { total += i; }\nitems.forEach(tally);` },
  { rule: "TS-ERROR:6", name: "a map whose answer is used is allowed", expect: "silent",
    code: `const waiting = items.map(async (i) => { await save(i); });\nawait Promise.all(waiting);` },
  { rule: "TS-ERROR:6", name: "forEach with a named async handler", expect: "fires",
    code: `async function save(i: number) { await write(i); }\nitems.forEach(save);` },
  { rule: "TS-ERROR:6", name: "map with async, never awaited", expect: "fires",
    code: `items.map(async (i) => { await save(i); });` },

  { rule: "TS-LAYER:2", name: "control: require in a function", expect: "fires",
    code: `function f(){ const m = require("./m"); return m; }` },
  { rule: "TS-LAYER:2", name: "control: dynamic import in a function", expect: "fires",
    code: `async function f(){ const m = await import("./m"); return m; }` },
  { rule: "TS-LAYER:2", name: "alias require", expect: "fires",
    code: `const r = require; function f(){ return r("./m"); }` },
  { rule: "TS-LAYER:2", name: "createRequire", expect: "fires",
    code: `import { createRequire } from "node:module";\nfunction f(){ return createRequire(import.meta.url)("./m"); }` },

  { rule: "TS-TYPE:5", name: "control: parseInt no radix", expect: "fires", code: `const n = parseInt(s);` },
  { rule: "TS-TYPE:5", name: "Number.parseInt no radix", expect: "fires", code: `const n = Number.parseInt(s);` },
  { rule: "TS-TYPE:5", name: "control: double tilde", expect: "fires", code: `const n = ~~s;` },
  { rule: "TS-TYPE:5", name: "shift by zero", expect: "fires", code: `const n = s >> 0;` },
  { rule: "TS-TYPE:5", name: "parseInt with radix is allowed", expect: "silent", code: `const n = parseInt(s, 10);` },

  { rule: "TS-TYPE:2", name: "control: exported nullable return", expect: "fires",
    code: `export function f(): string | null { return null; }` },
  { rule: "TS-TYPE:2", name: "exported arrow const", expect: "fires",
    code: `export const f = (): string | null => null;` },
  { rule: "TS-TYPE:2", name: "nullable behind an alias", expect: "fires",
    code: `type Maybe = string | null;\nexport function f(): Maybe { return null; }` },
  { rule: "TS-TYPE:2", name: "export default", expect: "fires",
    code: `export default function f(): string | null { return null; }` },
  { rule: "TS-TYPE:2", name: "a declared function still promises what it promises", expect: "fires",
    code: `export declare function find(id: string): User | null;` },
  { rule: "TS-TYPE:4", name: "an enum is not any", expect: "silent",
    code: `export enum Colour { Red, Blue }` },
  { rule: "TS-TYPE:2", name: "wrapper generic is not a nullable return", expect: "silent",
    code: `export function f(): Box<string | null> { return box(); }` },

  { rule: "TS-DEAD:3", name: "control: empty exported function", expect: "fires",
    code: `export function f(): void {}` },
  { rule: "TS-DEAD:3", name: "bare return", expect: "fires",
    code: `export function f(): void { return; }` },
  { rule: "TS-DEAD:3", name: "control: not implemented", expect: "fires",
    code: `export function f(): void { throw new Error("not implemented"); }` },
  { rule: "TS-DEAD:3", name: "TODO instead of not implemented", expect: "fires",
    code: `export function f(): void { throw new Error("TODO"); }` },
  { rule: "TS-DEAD:3", name: "parameter property is not a stub", expect: "silent",
    code: `class A { constructor(private readonly x: number) {} }` },

  { rule: "DATA:1", name: "control: concatenated sql", expect: "fires",
    code: `const rows = db.query("SELECT * FROM users WHERE id = " + id);` },
  { rule: "DATA:1", name: "template literal sql", expect: "fires",
    code: "const rows = db.query(`SELECT * FROM users WHERE id = ${id}`);" },
  { rule: "DATA:1", name: "built one line earlier", expect: "fires",
    code: `const q = "SELECT * FROM users WHERE id = " + id;\nconst rows = db.query(q);` },
  { rule: "DATA:1", name: "built two lines earlier", expect: "fires",
    code: `const base = "SELECT * FROM users WHERE id = " + id;\nconst q = base;\nconst rows = db.query(q);` },
  { rule: "DATA:1", name: "parameters are allowed", expect: "silent",
    code: `const rows = db.query("SELECT * FROM users WHERE id = $1", [id]);` },
  { rule: "DATA:1", name: "a built string that is not sql is allowed", expect: "silent",
    code: "const label = `user ${id}`;\nconst rows = db.query(label);" },

  { rule: "NODE:1", name: "control: exec with concatenation", expect: "fires",
    code: `import { exec } from "node:child_process";\nexec("ls " + dir);` },
  { rule: "NODE:1", name: "template literal command", expect: "fires",
    code: "import { exec } from \"node:child_process\";\nexec(`ls ${dir}`);" },
  { rule: "NODE:1", name: "built one line earlier", expect: "fires",
    code: `import { execSync } from "node:child_process";\nconst cmd = "ls " + dir;\nexecSync(cmd);` },
  { rule: "NODE:1", name: "spawn with a shell", expect: "fires",
    code: "import { spawn } from \"node:child_process\";\nspawn(`ls ${dir}`, { shell: true });" },
  { rule: "NODE:1", name: "arguments kept as arguments is allowed", expect: "silent",
    code: `import { spawn } from "node:child_process";\nspawn("git", ["clone", url]);` },
  { rule: "NODE:1", name: "execFile with an array is allowed", expect: "silent",
    code: `import { execFile } from "node:child_process";\nexecFile("convert", [input, output]);` },
  { rule: "NODE:1", name: "a built string that never reaches a shell is allowed", expect: "silent",
    code: "const greeting = `hello ${name}`;\nlogger.info(greeting);" },
  { rule: "NODE:1", name: "a shell asked for by its name", expect: "fires",
    code: `import { spawn } from "node:child_process";\nspawn("sh", ["-c", \`git clone \${url}\`]);` },
  { rule: "NODE:1", name: "a shell asked for by its name, concatenated", expect: "fires",
    code: `import { spawnSync } from "node:child_process";\nspawnSync("bash", ["-c", "rm -rf " + dir]);` },
  { rule: "NODE:1", name: "a shell asked for by its path", expect: "fires",
    code: `import { execFile } from "node:child_process";\nexecFile("/bin/sh", ["-c", \`convert \${input}\`]);` },
  { rule: "NODE:1", name: "the interpreter for Windows counts too", expect: "fires",
    code: `import { spawn } from "node:child_process";\nspawn("cmd.exe", ["/c", \`del \${target}\`]);` },
  { rule: "NODE:1", name: "pasted with concat rather than plus", expect: "fires",
    code: `import { exec } from "node:child_process";\nexec("ls ".concat(dir));` },
  { rule: "NODE:1", name: "pasted by joining a list", expect: "fires",
    code: `import { exec } from "node:child_process";\nexec(["git", "clone", url].join(" "));` },
  { rule: "NODE:1", name: "a shell running a command nobody built is allowed", expect: "silent",
    code: `import { spawn } from "node:child_process";\nspawn("sh", ["-c", "ls -la"]);` },
  { rule: "NODE:1", name: "a program whose name merely starts with a shell's is allowed", expect: "silent",
    code: `import { spawn } from "node:child_process";\nspawn("shellcheck", ["-x", file]);` },
  { rule: "NODE:1", name: "a regular expression matching a built string is allowed", expect: "silent",
    code: `const AT_END = /[.!?]$/;\nconst found = AT_END.exec(parts.join(" "));` },
  { rule: "NODE:1", name: "a regular expression built with new RegExp is allowed", expect: "silent",
    code: `const found = new RegExp(pattern).exec("a " + b);` },
  { rule: "NODE:1", name: "a regular expression kept behind a namespace is allowed", expect: "silent",
    code: `const subnet = constants6.RE_SUBNET_STRING.exec(address + zone);` },
  { rule: "NODE:1", name: "a regular expression held in a variable is allowed", expect: "silent",
    code: `const AT_END = new RegExp("x");\nAT_END.exec(\`a \${b}\`);` },
  { rule: "NODE:1", name: "control: a member call named exec on a shell is not allowed", expect: "fires",
    code: `import childProcess from "node:child_process";\nchildProcess.exec(\`ls \${dir}\`);` },

  { rule: "DATA:2", name: "control: const from response.json", expect: "fires",
    code: `async function f(){ const body = await response.json(); return body.id; }` },
  { rule: "DATA:2", name: "assigned to an existing variable", expect: "fires",
    code: `async function f(){ let body; body = await response.json(); return body.id; }` },
  { rule: "DATA:2", name: "returned straight out", expect: "fires",
    code: `async function f(){ return await response.json(); }` },
  { rule: "DATA:2", name: "request body in a handler", expect: "fires",
    code: `async function f(req){ const body = await req.json(); return body.id; }` },
  { rule: "DATA:2", name: "destructured on arrival", expect: "fires",
    code: `async function f(req){ const { id } = await req.json(); return id; }` },
  { rule: "DATA:2", name: "passed straight to something else", expect: "fires",
    code: `async function f(req){ return save(await req.json()); }` },
  { rule: "DATA:2", name: "assigned onto a property", expect: "fires",
    code: `async function f(req){ this.body = await req.json(); }` },
  { rule: "DATA:2", name: "form data, not json", expect: "fires",
    code: `async function f(req){ const body = await req.formData(); return body.get("id"); }` },
  { rule: "DATA:2", name: "drained and thrown away is allowed", expect: "silent",
    code: `async function f(res){ await res.json(); return retry(); }` },
  { rule: "DATA:2", name: "reading text is not reading a shape", expect: "silent",
    code: `async function f(res){ const body = await res.text(); return body.slice(0, 160); }` },
  { rule: "DATA:2", name: "text off a library's own object is not a body", expect: "silent",
    code: `function f(page){ page.on("console", (m) => { if (m.type() === "error") log(m.text()); }); }` },
  { rule: "DATA:2", name: "text checked by hand is not asked for a schema", expect: "silent",
    code: `function f(m){ const t = m.text(); if (typeof t !== "string") return; log(t.slice(0, 160)); }` },
  { rule: "DATA:2", name: "checked on the spot is allowed", expect: "silent",
    code: `async function f(req){ const order = OrderSchema.parse(await req.json()); return order; }` },
  { rule: "DATA:2", name: "checked one line later is allowed", expect: "silent",
    code: `async function f(req){ const body = await req.json(); const order = OrderSchema.parse(body); return order; }` },
  { rule: "DATA:2", name: "safeParse is allowed", expect: "silent",
    code: `async function f(req){ const body = await req.json(); const r = OrderSchema.safeParse(body); return r; }` },
  { rule: "DATA:2", name: "checked on the spot, then returned", expect: "silent",
    code: `async function f(req){ return OrderSchema.parse(await req.json()); }` },

  { rule: "REACT:1", name: "control: hook inside an if", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { if (on) { const [a] = useState(0); } return null; }` },
  { rule: "REACT:1", name: "hook behind a logical and", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { on && useState(0); return null; }` },
  { rule: "REACT:1", name: "hook in a ternary", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { const a = on ? useState(0) : null; return null; }` },
  { rule: "REACT:1", name: "hook after an early return", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { if (!on) return null; const [a] = useState(0); return null; }` },
  { rule: "REACT:1", name: "hook after a braced early return", expect: "fires", file: "C.tsx",
    code: `function C({ on }) { if (!on) { return null; } useState(0); return null; }` },
  { rule: "REACT:1", name: "a return at the end is not early", expect: "silent", file: "C.tsx",
    code: `function C() { useState(0); return null; }` },
  { rule: "REACT:1", name: "a return inside an effect is not the component's", expect: "silent", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { if (!id) return; load(id); }, [id]); return null; }` },
  { rule: "REACT:1", name: "hook inside a do-while", expect: "fires", file: "C.tsx",
    code: `function C({ n }) { do { useState(n); } while (n > 0); return null; }` },
  { rule: "REACT:1", name: "hook inside a for-in", expect: "fires", file: "C.tsx",
    code: `function C({ o }) { for (const k in o) { useState(k); } return null; }` },
  { rule: "REACT:1", name: "hook inside a switch", expect: "fires", file: "C.tsx",
    code: `function C({ k }) { switch (k) { case 1: useState(0); } return null; }` },
  { rule: "REACT:1", name: "hook inside a loop", expect: "fires", file: "C.tsx",
    code: `function C({ items }) { for (const i of items) { useState(i); } return null; }` },

  { rule: "REACT:2", name: "control: missing dependency", expect: "fires", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { load(id); }, []); return null; }` },
  { rule: "REACT:2", name: "missing a member dependency", expect: "fires", file: "C.tsx",
    code: `function C({ user }) { useEffect(() => { load(user.id); }, []); return null; }` },
  { rule: "REACT:2", name: "missing a prop reached through props", expect: "fires", file: "C.tsx",
    code: `function C(props) { useEffect(() => { load(props.id); }, []); return null; }` },
  { rule: "REACT:2", name: "missing a useState value", expect: "fires", file: "C.tsx",
    code: `function C() { const [id, setId] = useState(0); useEffect(() => { load(id); }, []); return null; }` },
  { rule: "REACT:2", name: "a field name that matches nothing is not a dependency", expect: "silent", file: "C.tsx",
    code: `function C({ user }) { const id = 1; useEffect(() => { send(user.id); }, [user]); return null; }` },
  { rule: "REACT:2", name: "declared inside the effect is allowed", expect: "silent", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { const n = id + 1; log(n); }, [id]); return null; }` },
  { rule: "REACT:2", name: "complete list is allowed", expect: "silent", file: "C.tsx",
    code: `function C({ id }) { useEffect(() => { load(id); }, [id]); return null; }` },
  { rule: "REACT:2", name: "a module constant cannot change between renders", expect: "silent", file: "C.tsx",
    code: `const LIMIT_MS = 25000; function C() { useEffect(() => { wait(LIMIT_MS); }, []); return null; }` },
  { rule: "REACT:2", name: "an imported value cannot change between renders", expect: "silent", file: "C.tsx",
    code: `import { LIMIT } from "./limits"; function C() { useEffect(() => { wait(LIMIT); }, []); return null; }` },
  { rule: "REACT:2", name: "a function declared at module scope cannot change", expect: "silent", file: "C.tsx",
    code: `function load() {} function C() { useEffect(() => { load(); }, []); return null; }` },
  { rule: "REACT:2", name: "a module constant a component shadows is still judged", expect: "fires", file: "C.tsx",
    code: `const LIMIT = 1; function C({ n }) { const LIMIT = n; useEffect(() => { wait(LIMIT); }, []); return null; }` },
  { rule: "REACT:2", name: "a module let can be reassigned, so it is still judged", expect: "fires", file: "C.tsx",
    code: `let limit = 1; function C() { useEffect(() => { wait(limit); }, []); return null; }` },
  { rule: "REACT:2", name: "a type name a parameter is annotated with is not a dependency", expect: "silent", file: "C.tsx",
    code: `type S = "a"; function pick(at: S) { return at; } function C() { useEffect(() => { const v = read() as S; log(v); }, []); return null; }` },
  { rule: "REACT:2", name: "a global whose name appears in a type is not a dependency", expect: "silent", file: "C.tsx",
    code: `function pick(held: Set<string>) { return held; } function C() { useEffect(() => { log(new Set(["a"])); }, []); return null; }` },
  { rule: "REACT:2", name: "a type name a variable is annotated with is not a dependency", expect: "silent", file: "C.tsx",
    code: `type S = "a"; const at: S = "a"; function C() { useEffect(() => { const v = read() as S; log(v); }, []); return null; }` },
  { rule: "REACT:2", name: "a missing dependency in a typed component is still caught", expect: "fires", file: "C.tsx",
    code: `type S = "a"; function C({ at }: { at: S }) { useEffect(() => { load(at); }, []); return null; }` },
  { rule: "REACT:2", name: "a name caught by a catch inside the effect is not a dependency", expect: "silent", file: "C.tsx",
    code: `function other(cause) { return cause; } function C() { useEffect(() => { try { go(); } catch (cause) { log(cause); } }, []); return null; }` },
  { rule: "REACT:2", name: "a global named by a parameter of another function is not a dependency", expect: "silent", file: "C.tsx",
    code: `function other(window) { return window; } function C() { useEffect(() => { log(typeof window); }, []); return null; }` },
  { rule: "REACT:2", name: "a value from an enclosing component is still a dependency", expect: "fires", file: "C.tsx",
    code: `function Outer({ id }) { function Inner() { useEffect(() => { load(id); }, []); return null; } return Inner; }` },
  { rule: "REACT:2", name: "a value computed in the component is not a module constant", expect: "fires", file: "C.tsx",
    code: `const LIMIT_MS = 25000; function C({ n }) { const wait = n * LIMIT_MS; useEffect(() => { go(wait); }, []); return null; }` },

  { rule: "TS-ERROR:9", name: "control: waiting a guessed number of milliseconds", expect: "fires",
    code: `export async function go(): Promise<void> { await new Promise((resolve) => setTimeout(resolve, 500)); }` },
  { rule: "TS-ERROR:9", name: "the timers-promises spelling is the same guess", expect: "fires",
    code: `import { setTimeout as sleep } from "node:timers/promises";\nexport async function go(): Promise<void> { await sleep(500); }` },
  { rule: "TS-ERROR:9", name: "a helper called sleep given a number is a duration", expect: "fires",
    code: `export async function go(): Promise<void> { await sleep(200); }` },
  { rule: "TS-ERROR:9", name: "a sleep inside a loop is pacing, not guessing", expect: "silent",
    code: `export async function go(): Promise<void> { while (!done()) { await new Promise((resolve) => setTimeout(resolve, 100)); } }` },
  { rule: "TS-ERROR:9", name: "a sleep inside a for-of is pacing between items", expect: "silent",
    code: `export async function go(items: readonly string[]): Promise<void> { for (const item of items) { await send(item); await sleep(50); } }` },
  { rule: "TS-ERROR:9", name: "a timer that is not waited for schedules work, it does not guess", expect: "silent",
    code: `export function later(run: () => void): void { setTimeout(run, 500); }` },
  { rule: "TS-ERROR:9", name: "waiting for the thing itself is the shape the rule wants", expect: "silent",
    code: `export async function go(): Promise<void> { await untilReady(); }` },
  { rule: "TS-ERROR:9", name: "a promise built around something other than a timer is not a sleep", expect: "silent",
    code: `export async function go(): Promise<void> { await new Promise((resolve) => stream.on("end", resolve)); }` },
  { rule: "TS-ERROR:9", name: "a timer with no delay yields a tick rather than guessing a duration", expect: "silent",
    code: `export async function go(): Promise<void> { await new Promise((resolve) => setTimeout(resolve)); }` },
  { rule: "TS-ERROR:9", name: "a promise that does real work and also sets a timeout is doing the work", expect: "silent",
    code: `export async function go(socket: Socket): Promise<void> {\n  await new Promise((resolve, reject) => {\n    socket.on("open", resolve);\n    setTimeout(reject, 5000);\n  });\n}` },
  { rule: "TS-ERROR:9", name: "the delay in a variable is still a fixed wait", expect: "fires",
    code: `export async function go(pause: number): Promise<void> { await new Promise((resolve) => setTimeout(resolve, pause)); }` },

  { rule: "TS-ERROR:10", name: "control: a built-in error thrown from a catch", expect: "fires",
    code: `export function read(path: string): string { try { return open(path); } catch (cause) { throw new Error("could not read"); } }` },
  { rule: "TS-ERROR:10", name: "a TypeError from a catch loses the same trace", expect: "fires",
    code: `export function read(path: string): string { try { return open(path); } catch (cause) { throw new TypeError("bad path"); } }` },
  { rule: "TS-ERROR:10", name: "carrying the cause does not put the name back", expect: "fires",
    code: `export function read(path: string): string { try { return open(path); } catch (cause) { throw new Error("could not read", { cause }); } }` },
  { rule: "TS-ERROR:10", name: "a named error is the shape the rule wants", expect: "silent",
    code: `export function read(path: string): string { try { return open(path); } catch (cause) { throw new CouldNotRead(path, cause); } }` },
  { rule: "TS-ERROR:10", name: "rethrowing the original keeps everything", expect: "silent",
    code: `export function read(path: string): string { try { return open(path); } catch (cause) { log(cause); throw cause; } }` },
  { rule: "TS-ERROR:10", name: "a built-in error thrown where nothing was caught is not this rule", expect: "silent",
    code: `export function read(path: string): string { if (path.length === 0) { throw new Error("empty path"); } return open(path); }` },
  { rule: "TS-ERROR:10", name: "a throw inside a function defined in the catch is that function's throw", expect: "silent",
    code: `export function read(path: string): string { try { return open(path); } catch (cause) { return recover(() => { throw new Error("later"); }, cause); } }` },

  { rule: "TS-SECURITY:1", name: "control: eval", expect: "fires",
    code: `export function run(said: string): unknown { return eval(said); }` },
  { rule: "TS-SECURITY:1", name: "the Function constructor is eval with another name", expect: "fires",
    code: `export function run(said: string): unknown { return new Function(said)(); }` },
  { rule: "TS-SECURITY:1", name: "reaching it through globalThis is the same call", expect: "fires",
    code: `export function run(said: string): unknown { return globalThis.eval(said); }` },
  { rule: "TS-SECURITY:1", name: "a local function somebody called eval is theirs", expect: "silent",
    code: `function evaluate(said: string): number { return Number(said); }\nexport function run(said: string): number { return evaluate(said); }` },
  { rule: "TS-SECURITY:1", name: "reading a value out of a table is not conjuring code", expect: "silent",
    code: `export function run(name: string, table: Record<string, () => number>): number { const held = table[name]; if (held === undefined) { throw new Unknown(name); } return held(); }` },

  { rule: "TS-TYPE:6", name: "control: the round trip used as a deep copy", expect: "fires",
    code: `export function copy(held: object): unknown { return JSON.parse(JSON.stringify(held)); }` },
  { rule: "TS-TYPE:6", name: "the round trip is still the round trip when it is spread over names", expect: "fires",
    code: `export function copy(held: object): unknown { const text = JSON.stringify(held); return JSON.parse(text); }` },
  { rule: "TS-TYPE:6", name: "structuredClone is the shape the rule wants", expect: "silent",
    code: `export function copy(held: object): unknown { return structuredClone(held); }` },
  { rule: "TS-TYPE:6", name: "parsing something that arrived as text is not a copy", expect: "silent",
    code: `export function read(text: string): unknown { return JSON.parse(text); }` },
  { rule: "TS-TYPE:6", name: "writing a value out as text is not a copy", expect: "silent",
    code: `export function write(held: object): string { return JSON.stringify(held); }` },
  { rule: "TS-TRUTH:3", name: "control: a hex written where the code paints", expect: "fires",
    code: `export const INK = "#f1ece4";` },
  { rule: "TS-TRUTH:3", name: "three digits are still a hex", expect: "fires",
    code: `declare const ctx: CanvasRenderingContext2D; ctx.fillStyle = "#000";` },
  { rule: "TS-TRUTH:3", name: "four and eight digits carry an alpha", expect: "fires",
    code: `export const GLASS = "#0008"; export const INK = "#f1ece4cc";` },
  { rule: "TS-TRUTH:3", name: "a colour function with numbers in it", expect: "fires",
    code: `export const GROUND = "rgba(19, 16, 13, .92)";` },
  { rule: "TS-TRUTH:3", name: "hsl and oklch are colours too", expect: "fires",
    code: `export const HUE = "hsl(210 40% 50%)"; export const LAB = "oklch(70% 0.1 30)";` },
  { rule: "TS-TRUTH:3", name: "a gradient carries its stops", expect: "fires",
    code: `export const BACK = "linear-gradient(180deg, #3a4a3a 0%, #2c3830 100%)";` },
  { rule: "TS-TRUTH:3", name: "single quotes and an object table are the same colour", expect: "fires",
    code: `export const styles = { card: { shadowColor: '#000' } };` },
  { rule: "TS-TRUTH:3", name: "a template with no holes is a string", expect: "fires",
    code: "export const BACK = `url(a.png), rgba(0, 0, 0, .5)`;" },
  { rule: "TS-TRUTH:3", name: "an SVG attribute in JSX is a string", expect: "fires", file: "src/Icon.tsx",
    code: `export const Dot = () => <circle r="2" fill="#fff" />;` },
  { rule: "TS-TRUTH:3", name: "the palette file by its default name is where a colour lives", expect: "silent", file: "src/tokens.css",
    code: `export const INK = "#f1ece4";` },
  { rule: "TS-TRUTH:3", name: "a hex inside prose is a reference, not a colour", expect: "silent",
    code: `export const NOTE = "fixes #1234 and #abcdef in the docs";` },
  { rule: "TS-TRUTH:3", name: "an id handed to querySelector is a selector", expect: "silent",
    code: `export const face = document.querySelector("#face");` },
  { rule: "TS-TRUTH:3", name: "a colour built from values is not a literal", expect: "silent",
    code: "export const mix = (r: number, g: number, b: number) => `rgba(${r}, ${g}, ${b}, 1)`;" },
  { rule: "TS-TRUTH:3", name: "a colour built from tokens is not a literal", expect: "silent",
    code: `export const INK = "rgb(var(--r), var(--g), var(--b))";` },
  { rule: "TS-TRUTH:3", name: "the color() function names its space first", expect: "fires",
    code: `export const WIDE = "color(display-p3 1 0.5 0)";` },
  { rule: "TS-TRUTH:3", name: "a shader's own function is not the CSS one", expect: "silent",
    code: `export const SHADER = "vec4 color(vec2 coords, float blur) { return vec4(1.0); }";` },
  { rule: "TS-TRUTH:3", name: "a function of names is not a colour", expect: "silent",
    code: `export const NOTE = "rgb(red, green, 2)";` },
  { rule: "TS-TRUTH:3", name: "five digits are not a colour", expect: "silent",
    code: `export const CODE = "#12345";` },
  { rule: "TS-TRUTH:3", name: "hex letters without the hash are a word", expect: "silent",
    code: `export const SHA = "deadbeef";` },
  { rule: "TS-TRUTH:3", name: "a named colour is a word the rule does not read", expect: "silent",
    code: `export const INK = "red";` },
  { rule: "TS-TRUTH:3", name: "reading the palette is the shape the rule wants", expect: "silent",
    code: `export const ink = getComputedStyle(document.body).getPropertyValue("--ink");` },
  { rule: "TS-LAYER:3", name: "control: an inline style on an element", expect: "fires", file: "src/App.tsx",
    code: `export const A = ({ ink }: { ink: string }) => <div style={{ color: ink }}>hi</div>;` },
  { rule: "TS-LAYER:3", name: "a style held in a variable is still inline", expect: "fires", file: "src/App.tsx",
    code: `const box = { width: "100%" }; export const A = () => <div style={box}>hi</div>;` },
  { rule: "TS-LAYER:3", name: "an SVG element is a DOM element", expect: "fires", file: "src/App.tsx",
    code: `export const A = () => <circle r="2" style={{ fill: "currentColor" }} />;` },
  { rule: "TS-LAYER:3", name: "a custom property beside a plain one does not pardon the plain one", expect: "fires", file: "src/App.tsx",
    code: `export const A = ({ tint }: { tint: string }) => <div style={{ "--tint": tint, color: tint }}>hi</div>;` },
  { rule: "TS-LAYER:3", name: "a spread hides what it sets", expect: "fires", file: "src/App.tsx",
    code: `const box = { width: "100%" }; export const A = () => <div style={{ ...box }}>hi</div>;` },
  { rule: "TS-LAYER:3", name: "a string style is still the attribute", expect: "fires", file: "src/App.tsx",
    code: `export const A = () => <div style="color: red">hi</div>;` },
  { rule: "TS-LAYER:3", name: "custom properties only is the shape the rule wants", expect: "silent", file: "src/App.tsx",
    code: `export const A = ({ tint }: { tint: string }) => <div style={{ "--tint": tint }}>hi</div>;` },
  { rule: "TS-LAYER:3", name: "a class is the other shape", expect: "silent", file: "src/App.tsx",
    code: `export const A = () => <div className="card">hi</div>;` },
  { rule: "TS-LAYER:3", name: "a component's style prop is the component's business", expect: "silent", file: "src/App.tsx",
    code: `declare const CardPicker: (p: { style: string }) => null; export const A = () => <CardPicker style="gold" />;` },
  { rule: "TS-LAYER:3", name: "a native view is not a DOM element", expect: "silent", file: "src/App.tsx",
    code: `declare const View: (p: { style: object }) => null; const styles = { card: {} }; export const A = () => <View style={styles.card} />;` },
  { rule: "TS-LAYER:3", name: "a member component is not a DOM element", expect: "silent", file: "src/App.tsx",
    code: `declare const Animated: { View: (p: { style: object }) => null }; export const A = () => <Animated.View style={{ opacity: 1 }} />;` },
  { rule: "TS-LAYER:3", name: "another attribute ending in style is not this one", expect: "silent", file: "src/App.tsx",
    code: `export const A = () => <div data-style="card">hi</div>;` },
  { rule: "TS-TRUTH:4", name: "a catch that answers by calling a second route", expect: "fires",
    code: `export async function read(): Promise<number> { try { return await primary(); } catch (cause) { warn(cause); return await secondary(); } }` },
  { rule: "TS-TRUTH:4", name: "an inline catch handler that routes around the failure", expect: "fires",
    code: `export function read(): Promise<number> { return primary().catch(() => secondary()); }` },
  { rule: "TS-TRUTH:4", name: "an or falling through to a call is a default, not a failed route", expect: "silent",
    code: `export function read(x: number | undefined): number { return x || slow(); }` },
  { rule: "TS-TRUTH:4", name: "a nullish default is TS-TRUTH:1's business, not this rule's", expect: "silent",
    code: `export function read(x: number | undefined): number { return x ?? slow(); }` },
  { rule: "TS-TRUTH:4", name: "an absence that returns a call is a case with an answer", expect: "silent",
    code: `export function read(row: Row | undefined): number { if (row === undefined) { return slow(); } return row.n; }` },
  { rule: "TS-TRUTH:4", name: "a falsy absence that returns a call is a case with an answer", expect: "silent",
    code: `export function read(row: Row | undefined): number { if (!row) { return slow(); } return row.n; }` },
  { rule: "TS-TRUTH:4", name: "a capability probed on navigator", expect: "fires",
    code: `export function can(): boolean { return typeof navigator.mediaDevices.getDisplayMedia === "function"; }` },
  { rule: "TS-TRUTH:4", name: "a name probed in window", expect: "fires",
    code: `export function can(): boolean { return "showOpenFilePicker" in window; }` },
  { rule: "TS-TRUTH:4", name: "a host member compared against undefined", expect: "fires",
    code: `export function can(): boolean { return globalThis.crypto !== undefined; }` },
  { rule: "TS-TRUTH:4", name: "the catch that throws it on is the shape the rule wants", expect: "silent",
    code: `export async function read(): Promise<number> { try { return await primary(); } catch (cause) { throw new CouldNotRead(cause); } }` },
  { rule: "TS-TRUTH:4", name: "a catch that answers with a named absence", expect: "silent",
    code: `export async function read(): Promise<Held> { try { return { kind: "at", n: await primary() }; } catch (cause) { warn(cause); return { kind: "absent" }; } }` },
  { rule: "TS-TRUTH:4", name: "a catch that converts the cause it was handed", expect: "silent",
    code: `export function read(): string { try { return primary(); } catch (cause) { return String(cause); } }` },
  { rule: "TS-TRUTH:4", name: "narrowing a parsed payload is a guard, not a probe", expect: "silent",
    code: `export function held(parsed: unknown): number { if (parsed === null || typeof parsed !== "object") { return 0; } return 1; }` },
  { rule: "TS-TRUTH:4", name: "a boolean disjunction of two calls is not a default", expect: "silent",
    code: `export function held(x: number): boolean { return isA(x) || isB(x); }` },
  { rule: "TS-TRUTH:4", name: "an absence that throws names it", expect: "silent",
    code: `export function read(row: Row | undefined): number { if (row === undefined) { throw new NotFound(); } return row.n; }` },
  { rule: "TS-TRUTH:4", name: "a presence test guarding the ordinary path is not a fallback", expect: "silent",
    code: `export function read(row: Row | undefined): number { if (row !== undefined) { return measure(row); } return 0; }` },
  { rule: "TS-TRUTH:4", name: "an or used as a condition", expect: "silent",
    code: `export function read(x: number, y: number): number { if (x === 0 || slow() > y) { return 1; } return 2; }` },
  { rule: "TS-TRUTH:4", name: "typeof function on a parameter is not a host probe", expect: "silent",
    code: `export function held(asked: unknown): boolean { return typeof asked === "function"; }` },
  { rule: "TS-TRUTH:4", name: "an absence answered by transforming the data in hand", expect: "silent",
    code: `export function picked(marks: readonly Mark[], lit: Set<number> | null): readonly number[] { if (lit === null) return marks.map((mark) => mark.id); return []; }` },
];
