export type CsharpCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly file?: string;
};

export const CSHARP_CASES: readonly CsharpCase[] = [
  { rule: "CS-ERROR:1", name: "a catch with nothing in it", expect: "fires",
    code: `class C {\n    void F() {\n        try { G(); } catch { }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "a catch holding only a comment, which handles nothing", expect: "fires",
    code: `class C {\n    void F() {\n        try { G(); } catch { /* never mind */ }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "a catch that names the failure and still drops it", expect: "fires",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (Exception) { }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "an empty catch spread over three lines", expect: "fires",
    code: `class C {\n    void F() {\n        try { G(); }\n        catch\n        {\n        }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "logged where somebody will read it", expect: "silent",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (Exception error) { Log(error); }\n    }\n    void G() { }\n    void Log(Exception e) { }\n}\n` },
  { rule: "CS-ERROR:1", name: "thrown onward", expect: "silent",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (Exception) { throw; }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "turned into a failure that has a name", expect: "silent",
    code: `using System;\nclass Missing : Exception { }\nclass C {\n    void F() {\n        try { G(); } catch (Exception error) { throw new Missing(); }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "an empty method body is not a catch", expect: "silent",
    code: `class C {\n    void F() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "a try with a finally and no catch at all", expect: "silent",
    code: `class C {\n    void F() {\n        try { G(); } finally { H(); }\n    }\n    void G() { }\n    void H() { }\n}\n` },

  { rule: "CS-ERROR:1", name: "naming the one failure being ignored, which is the C# spelling of suppress()", expect: "silent",
    code: `using Microsoft.JSInterop;\nclass C {\n    void F() {\n        try { G(); } catch (JSDisconnectedException) { }\n    }\n    void G() { }\n}\nnamespace Microsoft.JSInterop { class JSDisconnectedException : System.Exception { } }\n` },
  { rule: "CS-ERROR:1", name: "a when filter naming which failure is expected", expect: "silent",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (Exception error) when (Expected(error)) { }\n    }\n    void G() { }\n    bool Expected(Exception e) => true;\n}\n` },
  { rule: "CS-ERROR:1", name: "a named failure that is still not the everything type", expect: "silent",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (OperationCanceledException) { }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "SystemException is as wide as Exception and names as little", expect: "fires",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (SystemException) { }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "the everything type with a name on it is still the everything type", expect: "fires",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (Exception error) { }\n    }\n    void G() { }\n}\n` },

  { rule: "CS-ERROR:2", name: "a failure that says nothing about itself", expect: "fires",
    code: `using System;\nclass C {\n    void F() { throw new Exception("something went wrong"); }\n}\n` },
  { rule: "CS-ERROR:2", name: "the same failure written out in full", expect: "fires",
    code: `class C {\n    void F() { throw new System.Exception("something went wrong"); }\n}\n` },
  { rule: "CS-ERROR:2", name: "a failure a caller can tell apart", expect: "silent",
    code: `using System;\nclass C {\n    void F() { throw new InvalidOperationException("no dataset open"); }\n}\n` },
  { rule: "CS-ERROR:2", name: "a failure named for this codebase", expect: "silent",
    code: `using System;\nclass DatasetMissing : Exception { }\nclass C {\n    void F() { throw new DatasetMissing(); }\n}\n` },

  { rule: "CS-TYPE:1", name: "the null check silenced on a value", expect: "fires",
    code: `class C {\n    string? Name() => null;\n    int F() => Name()!.Length;\n}\n` },
  { rule: "CS-TYPE:1", name: "the null check silenced on the way into a variable", expect: "fires",
    code: `class C {\n    string? Name() => null;\n    void F() { string held = Name()!; }\n}\n` },
  { rule: "CS-TYPE:1", name: "asking first instead of silencing", expect: "silent",
    code: `class C {\n    string? Name() => null;\n    int F() => Name()?.Length ?? 0;\n}\n` },
  { rule: "CS-TYPE:1", name: "not, the everyday one, is a different operator", expect: "silent",
    code: `class C {\n    bool F(bool ready) => !ready;\n}\n` },
  { rule: "CS-TYPE:1", name: "two things being different is not a suppression", expect: "silent",
    code: `class C {\n    bool F(int a, int b) => a != b;\n}\n` },

  { rule: "CS-TRUTH:1", name: "work started that nobody can wait for", expect: "fires",
    code: `using System.Threading.Tasks;\nclass C {\n    async void F() { await Task.Delay(1); }\n}\n` },
  { rule: "CS-TRUTH:1", name: "the same, with an argument", expect: "fires",
    code: `using System.Threading.Tasks;\nclass C {\n    async void F(string name) { await Task.Delay(1); }\n}\n` },
  { rule: "CS-TRUTH:1", name: "a Task a caller can wait for", expect: "silent",
    code: `using System.Threading.Tasks;\nclass C {\n    async Task F() { await Task.Delay(1); }\n}\n` },
  { rule: "CS-TRUTH:1", name: "an event handler, where the runtime demands this shape", expect: "silent",
    code: `using System;\nusing System.Threading.Tasks;\nclass C {\n    async void OnClick(object sender, EventArgs e) { await Task.Delay(1); }\n}\n` },
  { rule: "CS-TRUTH:1", name: "not async at all", expect: "silent",
    code: `class C {\n    void F() { }\n}\n` },


  { rule: "CS-ERROR:3", name: "a failure answered with nothing at all", expect: "fires",
    code: `using System;\nclass C {\n    string F() {\n        try { return G(); } catch (Exception) { return null; }\n    }\n    string G() => "";\n}\n` },
  { rule: "CS-ERROR:3", name: "a failure answered with an empty list", expect: "fires",
    code: `using System;\nusing System.Collections.Generic;\nclass C {\n    List<string> F() {\n        try { return G(); } catch (Exception) { return new List<string>(); }\n    }\n    List<string> G() => new();\n}\n` },
  { rule: "CS-ERROR:3", name: "a failure answered with an empty array", expect: "fires",
    code: `using System;\nclass C {\n    string[] F() {\n        try { return G(); } catch (Exception) { return Array.Empty<string>(); }\n    }\n    string[] G() => [];\n}\n` },
  { rule: "CS-ERROR:3", name: "a failure answered with zero", expect: "fires",
    code: `using System;\nclass C {\n    int F() {\n        try { return G(); } catch (Exception) { return 0; }\n    }\n    int G() => 1;\n}\n` },
  { rule: "CS-ERROR:3", name: "a value the caller asked for, not one invented here", expect: "silent",
    code: `using System;\nclass C {\n    string F(string fallback) {\n        try { return G(); } catch (Exception) { return fallback; }\n    }\n    string G() => "";\n}\n` },
  { rule: "CS-ERROR:3", name: "returning after writing the failure down", expect: "silent",
    code: `using System;\nclass C {\n    string? F() {\n        try { return G(); } catch (Exception error) { Log(error); return null; }\n    }\n    string G() => "";\n    void Log(Exception e) { }\n}\n` },
  { rule: "CS-ERROR:3", name: "a return outside any catch", expect: "silent",
    code: `class C {\n    string? F() { return null; }\n}\n` },

  { rule: "CS-ERROR:3", name: "naming the failure and answering false, which is the Try pattern", expect: "silent",
    code: `using System;\nclass C {\n    bool F() {\n        try { G(); return true; } catch (OperationCanceledException) { return false; }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:3", name: "a filter naming the failure, answering false", expect: "silent",
    code: `using System;\nclass C {\n    bool F() {\n        try { G(); return true; } catch (Exception e) when (Expected(e)) { return false; }\n    }\n    void G() { }\n    bool Expected(Exception e) => true;\n}\n` },
  { rule: "CS-ERROR:3", name: "TryParse, where answering false is the whole contract", expect: "silent",
    code: `class C {\n    bool TryRead(string s, out int v) {\n        v = 0;\n        try { v = int.Parse(s); return true; } catch { return false; }\n    }\n}\n` },

  { rule: "CS-ERROR:4", name: "TryParse setting its out value and answering false", expect: "silent",
    code: `class C {\n    bool TryRead(string s, out string? v) {\n        try { v = s.Trim(); return true; } catch { v = null; return false; }\n    }\n}\n` },
  { rule: "CS-ERROR:4", name: "naming the failure and recovering from it", expect: "silent",
    code: `using System;\nclass C {\n    bool ready;\n    void F() {\n        try { G(); } catch (OperationCanceledException) { ready = false; }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:4", name: "a catch that never looks at what it caught", expect: "fires",
    code: `using System;\nclass C {\n    bool ready;\n    void F() {\n        try { G(); } catch (Exception) { ready = false; }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:4", name: "a catch that does housekeeping and forgets the failure", expect: "fires",
    code: `using System;\nclass C {\n    int tries;\n    void F() {\n        try { G(); } catch (Exception) { tries++; H(); }\n    }\n    void G() { }\n    void H() { }\n}\n` },
  { rule: "CS-ERROR:4", name: "written down through a logger", expect: "silent",
    code: `using System;\nclass C {\n    void F() {\n        try { G(); } catch (Exception error) { LogWarning(error); }\n    }\n    void G() { }\n    void LogWarning(Exception e) { }\n}\n` },
  { rule: "CS-ERROR:4", name: "thrown onward as something named", expect: "silent",
    code: `using System;\nclass Missing : Exception { }\nclass C {\n    void F() {\n        try { G(); } catch (Exception error) { throw new Missing(); }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:4", name: "the caught failure is read, so it was not ignored", expect: "silent",
    code: `using System;\nclass C {\n    string? why;\n    void F() {\n        try { G(); } catch (Exception error) { why = error.Message; }\n    }\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:4", name: "an empty catch belongs to the other rule, not this one", expect: "silent",
    code: `class C {\n    void F() {\n        try { G(); } catch { }\n    }\n    void G() { }\n}\n` },

  { rule: "CS-LOG:1", name: "output taken from whoever ran the program", expect: "fires",
    code: `using System;\nclass C {\n    void F() { Console.WriteLine("saved"); }\n}\n` },
  { rule: "CS-LOG:1", name: "the error stream is no different", expect: "fires",
    code: `using System;\nclass C {\n    void F() { Console.Error.WriteLine("failed"); }\n}\n` },
  { rule: "CS-LOG:1", name: "the file that starts the program owns its own output", expect: "silent", file: "Program.cs",
    code: `using System;\nclass Program {\n    static void Main() { Console.WriteLine("started"); }\n}\n` },
  { rule: "CS-LOG:1", name: "a logger, which is where diagnostics go", expect: "silent",
    code: `class C {\n    void F() { LogInformation("saved"); }\n    void LogInformation(string m) { }\n}\n` },

  { rule: "CS-SECURITY:1", name: "a value pasted into the text of a query", expect: "fires",
    code: `class C {\n    string F(string id) => $"SELECT * FROM Data WHERE id = '{id}'";\n}\n` },
  { rule: "CS-SECURITY:1", name: "the same built by adding strings together", expect: "fires",
    code: `class C {\n    string F(string id) => "SELECT * FROM Data WHERE id = '" + id + "'";\n}\n` },
  { rule: "CS-SECURITY:1", name: "a column name pasted in is still pasted in", expect: "fires",
    code: `class C {\n    string F(string col) => $"SELECT {col} FROM Data";\n}\n` },
  { rule: "CS-SECURITY:1", name: "the value travels as a parameter, not as text", expect: "silent",
    code: `class C {\n    string F() => "SELECT * FROM Data WHERE id = @id";\n}\n` },
  { rule: "CS-SECURITY:1", name: "a label that says Select to a person, not to a database", expect: "silent",
    code: `class C {\n    string F(string name) => $"Select {name}";\n}\n` },
  { rule: "CS-LOG:1", name: "a script file is the program, so its output is its own", expect: "silent", file: "watch.cs",
    code: `#!/usr/bin/env dotnet\nusing System;\nConsole.WriteLine("watching");\n` },
  { rule: "CS-SECURITY:1", name: "a sentence that merely mentions a word", expect: "silent",
    code: `class C {\n    string F(string name) => $"Could not update {name}";\n}\n` },

  { rule: "CS-ERROR:1", name: "a swallowed failure inside a Razor code block", expect: "fires", file: "Held.razor",
    code: `<div>@Name</div>\n\n@code {\n    string Name = "";\n\n    void F() {\n        try { G(); } catch { }\n    }\n\n    void G() { }\n}\n` },
  { rule: "CS-TRUTH:1", name: "work nobody can wait for, inside a Razor code block", expect: "fires", file: "Held.razor",
    code: `<div>@Name</div>\n\n@code {\n    string Name = "";\n\n    async void F() { await System.Threading.Tasks.Task.Delay(1); }\n}\n` },
  { rule: "CS-ERROR:1", name: "a clean Razor code block", expect: "silent", file: "Held.razor",
    code: `<div>@Name</div>\n\n@code {\n    string Name = "";\n\n    void F() {\n        try { G(); } catch (System.Exception error) { System.Console.Error.WriteLine(error); }\n    }\n\n    void G() { }\n}\n` },
  { rule: "CS-ERROR:1", name: "markup outside the code block is not read, and this records that", expect: "silent", file: "Held.razor",
    code: `<button @onclick="@(() => { try { G(); } catch { } })">go</button>\n\n@code {\n    void G() { }\n}\n` },
];
