import type { Case } from "./cases.ts";

const A_PAGE = "public/index.html";

const A_SHEET = "src/app.css";

const A_SASS_SHEET = "src/app.scss";

const THE_PALETTE = "src/tokens.css";

export const CSS_CASES: readonly Case[] = [
  { rule: "CSS-LAYER:1", name: "control: a style attribute on an element", expect: "fires", file: A_PAGE,
    code: `<div style="color: red">hi</div>` },
  { rule: "CSS-LAYER:1", name: "spaces around the equals do not hide it", expect: "fires", file: A_PAGE,
    code: `<div STYLE = "color: red">hi</div>` },
  { rule: "CSS-LAYER:1", name: "an attribute whose value contains > is still one tag", expect: "fires", file: A_PAGE,
    code: `<img alt="a>b" src="a.png" style="margin:0">` },
  { rule: "CSS-LAYER:1", name: "a class and a stylesheet is the shape the rule wants", expect: "silent", file: A_PAGE,
    code: `<div class="card">hi</div>` },
  { rule: "CSS-LAYER:1", name: "another attribute ending in style is not this one", expect: "silent", file: A_PAGE,
    code: `<div data-style="card">hi</div>` },
  { rule: "CSS-LAYER:1", name: "style= inside an attribute value is data, not an attribute", expect: "silent", file: A_PAGE,
    code: `<div data-note="style=nope">hi</div>` },
  { rule: "CSS-LAYER:1", name: "a commented-out element is not on the page", expect: "silent", file: A_PAGE,
    code: `<!-- <div style="color:red"></div> -->` },
  { rule: "CSS-LAYER:1", name: "a script that writes the word is not an attribute", expect: "silent", file: A_PAGE,
    code: `<script>const held = ' style="color:red" ';</script>` },
  { rule: "CSS-LAYER:1", name: "a stylesheet has no elements to carry the attribute", expect: "silent", file: A_SHEET,
    code: `.card { color: var(--color-ink); }` },

  { rule: "CSS-TRUTH:1", name: "control: a hex written where it is used", expect: "fires", file: A_SHEET,
    code: `.card { color: #ff0088; }` },
  { rule: "CSS-TRUTH:1", name: "three digits and eight digits are both hexes", expect: "fires", file: A_SHEET,
    code: `.card { color: #f08; background: #ff008844; }` },
  { rule: "CSS-TRUTH:1", name: "a colour function with numbers in it is a literal", expect: "fires", file: A_SHEET,
    code: `.card { background: hsl(210 50% 40%); }` },
  { rule: "CSS-TRUTH:1", name: "one of the 148 names, on a property that takes a colour", expect: "fires", file: A_SHEET,
    code: `.card { border: 1px solid rebeccapurple; }` },
  { rule: "CSS-TRUTH:1", name: "a token defined outside the palette file is still a colour with two homes", expect: "fires", file: A_SHEET,
    code: `:root { --brand: #ff0088; }` },
  { rule: "CSS-TRUTH:1", name: "a Sass variable is a token by another spelling", expect: "fires", file: A_SASS_SHEET,
    code: `$brand: #ff0088;` },
  { rule: "CSS-TRUTH:1", name: "a page carries its stylesheet inside a style block", expect: "fires", file: A_PAGE,
    code: `<style>\n.card { color: #ff0088; }\n</style>` },
  { rule: "CSS-TRUTH:1", name: "the palette file is where a colour is allowed to be written out", expect: "silent", file: THE_PALETTE,
    code: `:root { --color-pink: #ff0088; --color-ink: black; }` },
  { rule: "CSS-TRUTH:1", name: "pointing at a token by name is the shape the rule wants", expect: "silent", file: A_SHEET,
    code: `.card { color: var(--color-pink); }` },
  { rule: "CSS-TRUTH:1", name: "a token name that contains a colour word is a name, not a colour", expect: "silent", file: A_SHEET,
    code: `.card { background: var(--color-pink); border-color: var(--red-500); }` },
  { rule: "CSS-TRUTH:1", name: "a colour built entirely from tokens has no literal in it", expect: "silent", file: A_SHEET,
    code: `.card { background: hsl(var(--brand-h) var(--brand-s) var(--brand-l)); }` },
  { rule: "CSS-TRUTH:1", name: "a colour named in a comment is a comment", expect: "silent", file: A_SHEET,
    code: `/* the old brand was #ff0088, near red */\n.card { color: var(--color-ink); }` },
  { rule: "CSS-TRUTH:1", name: "a colour word inside a quoted string is text", expect: "silent", file: A_SHEET,
    code: `.card::after { content: "#ff0088 red"; }` },
  { rule: "CSS-TRUTH:1", name: "Arial Black is a font, because font-family carries no colour", expect: "silent", file: A_SHEET,
    code: `.card { font-family: Arial Black, sans-serif; }` },
  { rule: "CSS-TRUTH:1", name: "a hex-shaped id selector is a selector", expect: "silent", file: A_SHEET,
    code: `#face { padding: 0; }\n#beef .dad { margin: 0; }` },
  { rule: "CSS-TRUTH:1", name: "a colour inside a data URI belongs to the image, not the sheet", expect: "silent", file: A_SHEET,
    code: `.card { background: url("data:image/svg+xml,<svg><g transform='translate(2,2)' stroke='black'/></svg>"); }` },
  { rule: "CSS-TRUTH:1", name: "a fragment on an image address is not a hex", expect: "silent", file: A_SHEET,
    code: `.card { background: url(/img/sprite.svg#fff); }` },
  { rule: "CSS-TRUTH:1", name: "a colour behind a Sass line comment is a comment", expect: "silent", file: A_SASS_SHEET,
    code: `.card {\n  // color: red;\n  color: var(--color-ink);\n}` },
  { rule: "CSS-TRUTH:1", name: "linear is a timing word, not a colour", expect: "silent", file: A_SHEET,
    code: `.card { transition: color 0.2s linear; }` },

  { rule: "CSS-TRUTH:2", name: "control: a z-index past the cap", expect: "fires", file: A_SHEET,
    code: `.modal { z-index: 9999; }` },
  { rule: "CSS-TRUTH:2", name: "moving the number into a token does not move it below the cap", expect: "fires", file: A_SHEET,
    code: `:root { --z-modal: 9999; }` },
  { rule: "CSS-TRUTH:2", name: "the largest number the property takes is the end of the war", expect: "fires", file: A_SHEET,
    code: `.toast { z-index: 2147483647; }` },
  { rule: "CSS-TRUTH:2", name: "a layer inside the cap is a scale", expect: "silent", file: A_SHEET,
    code: `.modal { z-index: 40; }` },
  { rule: "CSS-TRUTH:2", name: "the cap itself is allowed", expect: "silent", file: A_SHEET,
    code: `.modal { z-index: 100; }` },
  { rule: "CSS-TRUTH:2", name: "a negative z-index puts a thing behind, which is an order like any other", expect: "silent", file: A_SHEET,
    code: `.backdrop { z-index: -1; }` },
  { rule: "CSS-TRUTH:2", name: "naming the layer is the shape the rule wants", expect: "silent", file: A_SHEET,
    code: `.modal { z-index: var(--z-modal); }` },
  { rule: "CSS-TRUTH:2", name: "a width past the cap is not a stacking order", expect: "silent", file: A_SHEET,
    code: `.page { max-width: 1200px; }` },

  { rule: "CSS-TRUTH:3", name: "control: a negative margin", expect: "fires", file: A_SHEET,
    code: `.card { margin-top: -8px; }` },
  { rule: "CSS-TRUTH:3", name: "one negative side inside a shorthand is still a negative margin", expect: "fires", file: A_SHEET,
    code: `.card { margin: 0 -1rem 0 0; }` },
  { rule: "CSS-TRUTH:3", name: "the logical properties are margins too", expect: "fires", file: A_SHEET,
    code: `.card { margin-inline-start: -2px; }` },
  { rule: "CSS-TRUTH:3", name: "a value spread over several lines is one declaration", expect: "fires", file: A_SHEET,
    code: `.card {\n  margin:\n    0\n    -4px;\n}` },
  { rule: "CSS-TRUTH:3", name: "subtraction inside calc is arithmetic, not a negative margin", expect: "silent", file: A_SHEET,
    code: `.card { margin-top: calc(var(--space-4) - var(--border)); }` },
  { rule: "CSS-TRUTH:3", name: "a token whose name ends in a number is a name", expect: "silent", file: A_SHEET,
    code: `.card { margin: var(--space-2); }` },
  { rule: "CSS-TRUTH:3", name: "a negative offset is not a margin", expect: "silent", file: A_SHEET,
    code: `.card { top: -8px; }` },
  { rule: "CSS-TRUTH:3", name: "spacing owned by the container is the shape the rule wants", expect: "silent", file: A_SHEET,
    code: `.list { display: grid; gap: var(--space-2); }` },

  { rule: "CSS-TYPE:1", name: "control: an important", expect: "fires", file: A_SHEET,
    code: `.card { color: var(--color-ink) !important; }` },
  { rule: "CSS-TYPE:1", name: "casing and spacing do not hide it", expect: "fires", file: A_SHEET,
    code: `.card { display: none !  IMPORTANT; }` },
  { rule: "CSS-TYPE:1", name: "a page carries it inside a style block", expect: "fires", file: A_PAGE,
    code: `<style>\n.card { display: none !important; }\n</style>` },
  { rule: "CSS-TYPE:1", name: "the palette file is not excused from this one", expect: "fires", file: THE_PALETTE,
    code: `:root { --color-ink: #111 !important; }` },
  { rule: "CSS-TYPE:1", name: "the word inside a comment is a comment", expect: "silent", file: A_SHEET,
    code: `/* do not use !important here */\n.card { color: var(--color-ink); }` },
  { rule: "CSS-TYPE:1", name: "a Sass default is not an important", expect: "silent", file: A_SASS_SHEET,
    code: `$radius: 4px !default;` },
  { rule: "CSS-TYPE:1", name: "the word in a string is text", expect: "silent", file: A_SHEET,
    code: `.card::after { content: "!important"; }` },
];
