export type PythonCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
};

export const PYTHON_CASES: readonly PythonCase[] = [
  { rule: "PY-ERROR:1", name: "a bare except swallowing everything", expect: "fires",
    code: `def f(p):\n    try:\n        return open(p).read()\n    except:\n        return ""\n` },
  { rule: "PY-ERROR:1", name: "an except whose body is pass", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        pass\n` },
  { rule: "PY-ERROR:1", name: "an except that does nothing by ellipsis", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        ...\n` },
  { rule: "PY-ERROR:1", name: "catching everything and doing nothing", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except Exception:\n        pass\n` },
  { rule: "PY-ERROR:1", name: "a bare except is still bare when its body works", expect: "fires",
    code: `import logging\n\n\ndef f(p):\n    try:\n        open(p)\n    except:\n        logging.warning("could not open")\n` },
  { rule: "PY-ERROR:1", name: "logged and recovered from in the open", expect: "silent",
    code: `import logging\n\n\ndef f(p):\n    try:\n        open(p)\n    except OSError:\n        logging.warning("could not open %s", p)\n` },
  { rule: "PY-ERROR:1", name: "re-raised", expect: "silent",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        raise\n` },
  { rule: "PY-ERROR:1", name: "re-raised as something named, keeping the cause", expect: "silent",
    code: `class Missing(Exception):\n    pass\n\n\ndef f(p):\n    try:\n        open(p)\n    except OSError as error:\n        raise Missing(p) from error\n` },
  { rule: "PY-ERROR:1", name: "suppress names what is ignored, which pass never does", expect: "silent",
    code: `from contextlib import suppress\n\n\ndef f(p):\n    with suppress(FileNotFoundError):\n        open(p)\n` },
  { rule: "PY-ERROR:1", name: "a class body of pass is not an except", expect: "silent",
    code: `class Missing(Exception):\n    pass\n` },
  { rule: "PY-ERROR:1", name: "a function body of pass is not an except", expect: "silent",
    code: `def later():\n    pass\n` },
  { rule: "PY-ERROR:1", name: "a try with no except at all", expect: "silent",
    code: `def f(p):\n    try:\n        open(p)\n    finally:\n        print("done")\n` },
  { rule: "PY-TRUTH:1", name: "an empty list as a default", expect: "fires",
    code: `def add(item, items=[]):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "an empty dict as a default", expect: "fires",
    code: `def add(key, seen={}):\n    seen[key] = True\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a set built by calling set()", expect: "fires",
    code: `def add(item, seen=set()):\n    seen.add(item)\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a list built by calling list()", expect: "fires",
    code: `def add(item, items=list()):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a method argument is no different", expect: "fires",
    code: `class Basket:\n    def add(self, item, items=[]):\n        items.append(item)\n        return items\n` },
  { rule: "PY-TRUTH:1", name: "a keyword-only argument is no different", expect: "fires",
    code: `def add(item, *, items=[]):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a set written out in full", expect: "fires",
    code: `def add(item, seen={1, 2}):\n    seen.add(item)\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "None is the legal spelling", expect: "silent",
    code: `def add(item, items=None):\n    items = [] if items is None else items\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a tuple cannot be changed, so it is safe to share", expect: "silent",
    code: `def name(names=()):\n    return names\n` },
  { rule: "PY-TRUTH:1", name: "numbers and text cannot be changed either", expect: "silent",
    code: `def page(size=20, sort=""):\n    return size, sort\n` },
  { rule: "PY-TRUTH:1", name: "frozenset cannot be changed", expect: "silent",
    code: `def add(seen=frozenset()):\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a list built inside the body is a new one each call", expect: "silent",
    code: `def add(item):\n    items = []\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a name as a default is not a container this rule can see", expect: "silent",
    code: `EMPTY = ()\n\n\ndef add(names=EMPTY):\n    return names\n` },
];
