export type PythonCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly file?: string;
};

export const PYTHON_CASES: readonly PythonCase[] = [
  { rule: "PY-ERROR:1", name: "a bare except swallowing everything", expect: "fires",
    code: `def f(p):\n    try:\n        return open(p).read()\n    except:\n        return ""\n` },
  { rule: "PY-ERROR:1", name: "an except whose body is pass", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        pass\n` },
  { rule: "PY-ERROR:1", name: "an except that does nothing by ellipsis", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        ...\n` },
  { rule: "PY-ERROR:1", name: "catching everything and doing nothing", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except Exception:\n        pass\n` },
  { rule: "PY-ERROR:1", name: "a bare except is still bare when its body works", expect: "fires",
    code: `import logging\n\n\ndef f(p):\n    try:\n        open(p)\n    except:\n        logging.warning("could not open")\n` },
  { rule: "PY-ERROR:1", name: "logged and recovered from in the open", expect: "silent",
    code: `import logging\n\n\ndef f(p):\n    try:\n        open(p)\n    except OSError:\n        logging.warning("could not open %s", p)\n` },
  { rule: "PY-ERROR:1", name: "re-raised", expect: "silent",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        raise\n` },
  { rule: "PY-ERROR:1", name: "re-raised as something named, keeping the cause", expect: "silent",
    code: `class Missing(Exception):\n    pass\n\n\ndef f(p):\n    try:\n        open(p)\n    except OSError as error:\n        raise Missing(p) from error\n` },
  { rule: "PY-ERROR:1", name: "suppress names what is ignored, which pass never does", expect: "silent",
    code: `from contextlib import suppress\n\n\ndef f(p):\n    with suppress(FileNotFoundError):\n        open(p)\n` },
  { rule: "PY-ERROR:1", name: "a class body of pass is not an except", expect: "silent",
    code: `class Missing(Exception):\n    pass\n` },
  { rule: "PY-ERROR:1", name: "a function body of pass is not an except", expect: "silent",
    code: `def later():\n    pass\n` },
  { rule: "PY-ERROR:1", name: "a try with no except at all", expect: "silent",
    code: `def f(p):\n    try:\n        open(p)\n    finally:\n        print("done")\n` },
  { rule: "PY-TRUTH:1", name: "an empty list as a default", expect: "fires",
    code: `def add(item, items=[]):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "an empty dict as a default", expect: "fires",
    code: `def add(key, seen={}):\n    seen[key] = True\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a set built by calling set()", expect: "fires",
    code: `def add(item, seen=set()):\n    seen.add(item)\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a list built by calling list()", expect: "fires",
    code: `def add(item, items=list()):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a method argument is no different", expect: "fires",
    code: `class Basket:\n    def add(self, item, items=[]):\n        items.append(item)\n        return items\n` },
  { rule: "PY-TRUTH:1", name: "a keyword-only argument is no different", expect: "fires",
    code: `def add(item, *, items=[]):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a set written out in full", expect: "fires",
    code: `def add(item, seen={1, 2}):\n    seen.add(item)\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "None is the legal spelling", expect: "silent",
    code: `def add(item, items=None):\n    items = [] if items is None else items\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a tuple cannot be changed, so it is safe to share", expect: "silent",
    code: `def name(names=()):\n    return names\n` },
  { rule: "PY-TRUTH:1", name: "numbers and text cannot be changed either", expect: "silent",
    code: `def page(size=20, sort=""):\n    return size, sort\n` },
  { rule: "PY-TRUTH:1", name: "frozenset cannot be changed", expect: "silent",
    code: `def add(seen=frozenset()):\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a list built inside the body is a new one each call", expect: "silent",
    code: `def add(item):\n    items = []\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a name as a default is not a container this rule can see", expect: "silent",
    code: `EMPTY = ()\n\n\ndef add(names=EMPTY):\n    return names\n` },
  { rule: "PY-TRUTH:2", name: "a check on data written as an assert", expect: "fires",
    code: `def charge(amount):\n    assert amount > 0, "amount must be positive"\n    return amount\n` },
  { rule: "PY-TRUTH:2", name: "an assert narrowing a type", expect: "fires",
    code: `def read(proc):\n    assert proc.stdout is not None\n    return proc.stdout.read()\n` },
  { rule: "PY-TRUTH:2", name: "an internal invariant is still deleted by -O", expect: "fires",
    code: `def step(depth):\n    assert depth >= 0\n    return depth\n` },
  { rule: "PY-TRUTH:2", name: "a file named for tests is where assert belongs", expect: "silent",
    file: "test_charge.py",
    code: `def test_charge():\n    assert 1 + 1 == 2\n` },
  { rule: "PY-TRUTH:2", name: "a file ending in _test is the same", expect: "silent",
    file: "charge_test.py",
    code: `def test_charge():\n    assert 1 + 1 == 2\n` },
  { rule: "PY-TRUTH:2", name: "anything under a tests folder is the same", expect: "silent",
    file: "tests/checks.py",
    code: `def check():\n    assert 1 + 1 == 2\n` },
  { rule: "PY-TRUTH:2", name: "conftest is part of the test machinery", expect: "silent",
    file: "conftest.py",
    code: `def pytest_configure(config):\n    assert config is not None\n` },
  { rule: "PY-TRUTH:2", name: "raising is the legal spelling and survives -O", expect: "silent",
    code: `def charge(amount):\n    if amount <= 0:\n        raise ValueError("amount must be positive")\n    return amount\n` },
  { rule: "PY-TRUTH:2", name: "the word assert inside a name is not a statement", expect: "silent",
    code: `def assert_positive(amount):\n    if amount <= 0:\n        raise ValueError("no")\n    return amount\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with None", expect: "fires",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        return None\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with an empty list", expect: "fires",
    code: `def rows(path):\n    try:\n        return open(path).readlines()\n    except OSError:\n        return []\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with an empty string", expect: "fires",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        return ""\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with a zero", expect: "fires",
    code: `def size(path):\n    try:\n        return len(open(path).read())\n    except OSError:\n        return 0\n` },
  { rule: "PY-ERROR:2", name: "a bare return is None wearing a shorter name", expect: "fires",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        return\n` },
  { rule: "PY-ERROR:2", name: "answering with an empty dict", expect: "fires",
    code: `def held(path):\n    try:\n        return {"text": open(path).read()}\n    except OSError:\n        return {}\n` },
  { rule: "PY-ERROR:2", name: "re-raising says the failure happened", expect: "silent",
    code: `class Missing(Exception):\n    pass\n\n\ndef read(path):\n    try:\n        return open(path).read()\n    except OSError as error:\n        raise Missing(path) from error\n` },
  { rule: "PY-ERROR:2", name: "a handler that uses the error is doing something with it", expect: "silent",
    code: `import logging\n\n\ndef read(path):\n    try:\n        return open(path).read()\n    except OSError as error:\n        logging.warning("could not read %s: %s", path, error)\n        return None\n` },
  { rule: "PY-ERROR:2", name: "the same answer the try already gives is not made up", expect: "silent",
    code: `def held(flag):\n    try:\n        return None\n    except OSError:\n        return None\n` },
  { rule: "PY-ERROR:2", name: "a default the try also returns is not made up", expect: "silent",
    code: `def held(v):\n    try:\n        if v is None:\n            return 0.0\n        return float(v)\n    except ValueError:\n        return 0.0\n` },
  { rule: "PY-ERROR:2", name: "a default returned before the try is still the handler's own", expect: "fires",
    code: `def held(v):\n    if v is None:\n        return 0.0\n    try:\n        return float(v)\n    except ValueError:\n        return 0.0\n` },
  { rule: "PY-ERROR:2", name: "returning a real value from the handler is not a fabrication", expect: "silent",
    code: `def read(path, fallback):\n    try:\n        return open(path).read()\n    except OSError:\n        return fallback.read()\n` },
  { rule: "PY-SECURITY:1", name: "control: a shell command built with an f-string", expect: "fires",
    code: `import subprocess\n\n\ndef convert(source):\n    subprocess.run(f"convert {source} out.png", shell=True)\n` },
  { rule: "PY-SECURITY:1", name: "os.system is always a shell", expect: "fires",
    code: `import os\n\n\ndef convert(source):\n    os.system("convert " + source)\n` },
  { rule: "PY-SECURITY:1", name: "percent formatting pastes just as well", expect: "fires",
    code: `import os\n\n\ndef convert(source):\n    os.popen("convert %s" % source)\n` },
  { rule: "PY-SECURITY:1", name: "format pastes just as well", expect: "fires",
    code: `import subprocess\n\n\ndef convert(source):\n    subprocess.check_output("convert {}".format(source), shell=True)\n` },
  { rule: "PY-SECURITY:1", name: "getoutput runs a shell without saying so", expect: "fires",
    code: `import subprocess\n\n\ndef convert(source):\n    return subprocess.getoutput("convert " + source)\n` },
  { rule: "PY-SECURITY:1", name: "Popen with a shell and a built line", expect: "fires",
    code: `import subprocess\n\n\ndef convert(source):\n    subprocess.Popen("convert " + source, shell=True)\n` },
  { rule: "PY-SECURITY:1", name: "an argument list is the shape that works", expect: "silent",
    code: `import subprocess\n\n\ndef convert(source):\n    subprocess.run(["convert", source, "out.png"], check=True)\n` },
  { rule: "PY-SECURITY:1", name: "a shell with a line nobody outside wrote", expect: "silent",
    code: `import os\n\n\ndef listing():\n    os.system("ls -la")\n` },
  { rule: "PY-SECURITY:1", name: "a built line handed to something that is not a shell", expect: "silent",
    code: `def describe(source):\n    return "convert " + source\n` },
  { rule: "PY-SECURITY:1", name: "shell is off, so the list is passed through untouched", expect: "silent",
    code: `import subprocess\n\n\ndef convert(source):\n    subprocess.run(["convert", source], shell=False)\n` },
  { rule: "PY-SECURITY:2", name: "control: a query built with an f-string", expect: "fires",
    code: `def find(cursor, wanted):\n    cursor.execute(f"SELECT * FROM orders WHERE id = {wanted}")\n` },
  { rule: "PY-SECURITY:2", name: "percent formatting pastes into a query too", expect: "fires",
    code: `def find(cursor, wanted):\n    cursor.execute("SELECT * FROM orders WHERE id = %s" % wanted)\n` },
  { rule: "PY-SECURITY:2", name: "concatenation pastes into a query too", expect: "fires",
    code: `def find(cursor, wanted):\n    cursor.execute("SELECT * FROM orders WHERE id = " + wanted)\n` },
  { rule: "PY-SECURITY:2", name: "format pastes into a query too", expect: "fires",
    code: `def find(cursor, wanted):\n    cursor.execute("DELETE FROM orders WHERE id = {}".format(wanted))\n` },
  { rule: "PY-SECURITY:2", name: "executemany is the same door", expect: "fires",
    code: `def find(cursor, table):\n    cursor.executemany(f"INSERT INTO {table} VALUES (?)", rows)\n` },
  { rule: "PY-SECURITY:2", name: "pasting the placeholders and passing the values is the shape that works for a list", expect: "silent",
    code: `def find(cursor, wanted):\n    marks = ", ".join(["?"] * len(wanted))\n    return cursor.execute(f"SELECT id FROM orders WHERE id IN ({marks})", tuple(wanted))\n` },
  { rule: "PY-SECURITY:2", name: "a value turned into a number cannot carry a query", expect: "silent",
    code: `def find(cursor, wanted):\n    ids = ",".join(str(int(one)) for one in wanted)\n    cursor.execute(f"DELETE FROM orders WHERE id IN ({ids})")\n` },
  { rule: "PY-SECURITY:2", name: "a list joined without turning each one into a number still pastes", expect: "fires",
    code: `def find(cursor, wanted):\n    ids = ",".join(str(one.id) for one in wanted)\n    cursor.execute(f"DELETE FROM orders WHERE id IN ({ids})")\n` },
  { rule: "PY-SECURITY:2", name: "parameters are the shape that works", expect: "silent",
    code: `def find(cursor, wanted):\n    cursor.execute("SELECT * FROM orders WHERE id = ?", (wanted,))\n` },
  { rule: "PY-SECURITY:2", name: "a percent placeholder handed to the driver is not pasting", expect: "silent",
    code: `def find(cursor, wanted):\n    cursor.execute("SELECT * FROM orders WHERE id = %s", (wanted,))\n` },
  { rule: "PY-SECURITY:2", name: "a built string that is not a query is not this rule", expect: "silent",
    code: `def greet(cursor, name):\n    cursor.execute("PRAGMA " + name)\n` },
  { rule: "PY-SECURITY:2", name: "something else called execute is not a database", expect: "silent",
    code: `def run(pool, name):\n    pool.execute("start " + name)\n` },
  { rule: "PY-SECURITY:2", name: "a query nobody outside wrote is left alone", expect: "silent",
    code: `def all_orders(cursor):\n    cursor.execute("SELECT * FROM orders")\n` },
  { rule: "PY-LOG:1", name: "control: a library prints", expect: "fires",
    code: `def save(order):\n    print("saving", order)\n    return order\n` },
  { rule: "PY-LOG:1", name: "printing the failure instead of handing it back", expect: "fires",
    code: `def load(path):\n    try:\n        return open(path).read()\n    except OSError as error:\n        print(error)\n        raise\n` },
  { rule: "PY-LOG:1", name: "writing to stdout directly is the same decision", expect: "fires",
    code: `import sys\n\n\ndef save(order):\n    sys.stdout.write("saving\\n")\n    return order\n` },
  { rule: "PY-LOG:1", name: "writing to stderr directly is the same decision", expect: "fires",
    code: `import sys\n\n\ndef save(order):\n    sys.stderr.write("oh\\n")\n    return order\n` },
  { rule: "PY-LOG:3", name: "control: an f-string handed to a logger", expect: "fires",
    code: `import logging\n\nlogger = logging.getLogger(__name__)\n\n\ndef save(order):\n    logger.info(f"saved {order}")\n` },
  { rule: "PY-LOG:3", name: "percent formatting applied before the call", expect: "fires",
    code: `import logging\n\nlogger = logging.getLogger(__name__)\n\n\ndef save(order):\n    logger.warning("saved %s" % order)\n` },
  { rule: "PY-LOG:3", name: "format applied before the call", expect: "fires",
    code: `import logging\n\nlogger = logging.getLogger(__name__)\n\n\ndef save(order):\n    logger.error("saved {}".format(order))\n` },
  { rule: "PY-LOG:3", name: "the standard library's own lazy form stays legal", expect: "silent",
    code: `import logging\n\nlogger = logging.getLogger(__name__)\n\n\ndef save(order):\n    logger.info("saved %s", order)\n` },
  { rule: "PY-LOG:3", name: "a field beside a constant message", expect: "silent",
    code: `import logging\n\nlogger = logging.getLogger(__name__)\n\n\ndef save(order):\n    logger.info("saved", extra={"order": order})\n` },
  { rule: "PY-LOG:3", name: "no logging imported, so nothing here is a log line", expect: "silent",
    code: `def save(order, report):\n    report.info(f"saved {order}")\n` },
  { rule: "PY-LOG:1", name: "a file that says it starts the program may print", expect: "silent",
    code: `def run():\n    print("done")\n\n\nif __name__ == "__main__":\n    run()\n` },
  { rule: "PY-LOG:1", name: "the guard exempts the whole file, not only the lines it runs", expect: "silent",
    code: `def work():\n    print("reached through the guard, and by any importer too")\n\n\nif __name__ == "__main__":\n    work()\n` },
  { rule: "PY-LOG:1", name: "the file Python itself calls the entry point may print", expect: "silent",
    file: "src/tool/__main__.py",
    code: `def run():\n    print("done")\n\n\nrun()\n` },
  { rule: "PY-LOG:1", name: "a destination the caller supplied is the caller's decision", expect: "silent",
    code: `def dump(rows, out):\n    print(rows, file=out)\n` },
  { rule: "PY-LOG:1", name: "a destination that defaults to the caller's is still theirs", expect: "silent",
    code: `def dump(rows, file=None):\n    print(rows, file=file)\n` },
  { rule: "PY-LOG:1", name: "naming the terminal is the module choosing it again", expect: "fires",
    code: `import sys\n\n\ndef dump(rows):\n    print(rows, file=sys.stderr)\n` },
  { rule: "PY-LOG:1", name: "the module choosing stdout is the same choice", expect: "fires",
    code: `import sys\n\n\ndef dump(rows):\n    print(rows, file=sys.stdout)\n` },
  { rule: "PY-LOG:1", name: "a logger is the shape that works", expect: "silent",
    code: `import logging\n\nlogger = logging.getLogger(__name__)\n\n\ndef save(order):\n    logger.info("saving %s", order)\n    return order\n` },
  { rule: "PY-LOG:1", name: "handing the words back to the caller is not printing them", expect: "silent",
    code: `def describe(order):\n    return f"saving {order}"\n` },
  { rule: "PY-LOG:1", name: "a method called print on something else is not the builtin", expect: "silent",
    code: `def save(sheet, order):\n    sheet.print(order)\n    return order\n` },

  { rule: "PY-TYPE:1", name: "silencing the checker on a line", expect: "fires",
    code: `def total(rows):\n    return sum(rows)  # type: ignore\n` },
  { rule: "PY-TYPE:1", name: "silencing one named complaint is still silencing it", expect: "fires",
    code: `def total(rows):\n    return sum(rows)  # type: ignore[arg-type]\n` },
  { rule: "PY-TYPE:1", name: "turning the checker off for a whole file", expect: "fires",
    code: `# mypy: ignore-errors\n\n\ndef total(rows):\n    return sum(rows)\n` },
  { rule: "PY-TYPE:1", name: "an old-style type comment says what a thing is", expect: "silent",
    code: `def total(rows):\n    count = 0  # type: int\n    return count\n` },
  { rule: "PY-TYPE:1", name: "prose that mentions the marker is not the marker", expect: "silent",
    code: `def total(rows):\n    # we should never need a type: ignore in here\n    return sum(rows)\n` },
  { rule: "PY-TYPE:1", name: "an annotation is the honest way to say it", expect: "silent",
    code: `def total(rows: list[int]) -> int:\n    return sum(rows)\n` },
  { rule: "PY-TYPE:1", name: "a string that happens to contain the words", expect: "silent",
    code: `HELP = "pass type: ignore to skip"\n` },
  { rule: "PY-LAYER:1", name: "a star import from a module", expect: "fires",
    code: `from os.path import *\n\n\ndef where(p):\n    return join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "a star import from a package beside it", expect: "fires",
    code: `from .models import *\n\n\ndef held():\n    return Order\n` },
  { rule: "PY-LAYER:1", name: "naming what you take says where it came from", expect: "silent",
    code: `from os.path import join\n\n\ndef where(p):\n    return join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "importing the module keeps the name on it", expect: "silent",
    code: `import os.path\n\n\ndef where(p):\n    return os.path.join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "renaming one name is not taking all of them", expect: "silent",
    code: `from os import path as here\n\n\ndef where(p):\n    return here.join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "a multiplication is not an import", expect: "silent",
    code: `def area(w, h):\n    return w * h\n` },
  { rule: "PY-ERROR:3", name: "raising the base of everything", expect: "fires",
    code: `def charge(amount):\n    if amount <= 0:\n        raise Exception("amount must be positive")\n    return amount\n` },
  { rule: "PY-ERROR:3", name: "raising the base of even that", expect: "fires",
    code: `def charge(amount):\n    if amount <= 0:\n        raise BaseException("bad amount")\n    return amount\n` },
  { rule: "PY-ERROR:3", name: "raising the class itself is the same thing", expect: "fires",
    code: `def charge(amount):\n    if amount <= 0:\n        raise Exception\n    return amount\n` },
  { rule: "PY-ERROR:3", name: "a class of your own says which failure this is", expect: "silent",
    code: `class AmountNotPositive(Exception):\n    pass\n\n\ndef charge(amount):\n    if amount <= 0:\n        raise AmountNotPositive(amount)\n    return amount\n` },
  { rule: "PY-ERROR:3", name: "a built-in that names the kind of failure", expect: "silent",
    code: `def charge(amount):\n    if amount <= 0:\n        raise ValueError("amount must be positive")\n    return amount\n` },
  { rule: "PY-ERROR:3", name: "RuntimeError is a name a caller can catch on its own", expect: "silent",
    code: `def step(state):\n    if state is None:\n        raise RuntimeError("no state")\n    return state\n` },
  { rule: "PY-ERROR:3", name: "Exception as a base class is how you make a named one", expect: "silent",
    code: `class Missing(Exception):\n    pass\n` },
  { rule: "PY-ERROR:3", name: "catching is not raising", expect: "silent",
    code: `import logging\n\n\ndef read(path):\n    try:\n        return open(path).read()\n    except Exception as error:\n        logging.warning("failed: %s", error)\n        raise\n` },
  { rule: "PY-ERROR:3", name: "a bare re-raise keeps whatever it was", expect: "silent",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        raise\n` },

  { rule: "PY-ERROR:4", name: "control: waiting a guessed number of seconds", expect: "fires",
    code: `import time\n\n\ndef go():\n    start()\n    time.sleep(2)\n    return read()\n` },
  { rule: "PY-ERROR:4", name: "the async spelling is the same guess", expect: "fires",
    code: `import asyncio\n\n\nasync def go():\n    start()\n    await asyncio.sleep(2)\n    return read()\n` },
  { rule: "PY-ERROR:4", name: "imported by name, it is still a fixed wait", expect: "fires",
    code: `from time import sleep\n\n\ndef go():\n    start()\n    sleep(0.5)\n    return read()\n` },
  { rule: "PY-ERROR:4", name: "a sleep inside a while loop is pacing, not guessing", expect: "silent",
    code: `import time\n\n\ndef go():\n    while not ready():\n        time.sleep(0.5)\n    return read()\n` },
  { rule: "PY-ERROR:4", name: "a sleep inside a for loop paces the items", expect: "silent",
    code: `import time\n\n\ndef go(items):\n    for item in items:\n        send(item)\n        time.sleep(0.1)\n` },
  { rule: "PY-ERROR:4", name: "waiting for the thing itself is the shape the rule wants", expect: "silent",
    code: `def go():\n    start()\n    wait_until_ready()\n    return read()\n` },
  { rule: "PY-ERROR:4", name: "a method called sleep on something else is not the clock", expect: "silent",
    code: `def go(worker):\n    worker.sleep(2)\n` },
  { rule: "PY-ERROR:4", name: "sleeping zero yields to the loop, it does not guess a duration", expect: "silent",
    code: `import asyncio\n\n\nasync def go():\n    await asyncio.sleep(0)\n    return read()\n` },
  { rule: "PY-ERROR:4", name: "sleeping forever waits to be cancelled, which guesses nothing", expect: "silent",
    code: `import math\nimport asyncio\n\n\nasync def go():\n    await asyncio.sleep(math.inf)\n` },
  { rule: "PY-ERROR:4", name: "a duration the caller handed in is the caller's number, not a guess", expect: "silent",
    code: `import time\n\n\ndef measure(interval):\n    start()\n    time.sleep(interval)\n    return read()\n` },

  { rule: "PY-SECURITY:3", name: "a function the module defined called eval is the module's own", expect: "silent",
    code: `def eval(req, **env):\n    return not req.marker\n\n\ndef keep(reqs):\n    return [req for req in reqs if eval(req)]\n` },

  { rule: "PY-SECURITY:3", name: "control: eval on a string", expect: "fires",
    code: `def run(said):\n    return eval(said)\n` },
  { rule: "PY-SECURITY:3", name: "exec is the same door", expect: "fires",
    code: `def run(said):\n    exec(said)\n` },
  { rule: "PY-SECURITY:3", name: "compile builds the same code out of a string", expect: "fires",
    code: `def run(said):\n    return compile(said, "<given>", "exec")\n` },
  { rule: "PY-SECURITY:3", name: "a table from a name to a function is the shape the rule wants", expect: "silent",
    code: `def run(name, doing):\n    held = doing.get(name)\n    if held is None:\n        raise KeyError(name)\n    return held()\n` },
  { rule: "PY-SECURITY:3", name: "reading data that arrived as text is not running it", expect: "silent",
    code: `import json\n\n\ndef run(said):\n    return json.loads(said)\n` },
  { rule: "PY-SECURITY:3", name: "a method somebody called eval on their own object is theirs", expect: "silent",
    code: `def run(model, said):\n    return model.eval(said)\n` },

  { rule: "PY-TRUTH:3", name: "control: the global statement", expect: "fires",
    code: `count = 0\n\n\ndef bump():\n    global count\n    count += 1\n` },
  { rule: "PY-TRUTH:3", name: "nonlocal is bounded to the function above it, so it is not this rule", expect: "silent",
    code: `def outer():\n    count = 0\n\n    def bump():\n        nonlocal count\n        count += 1\n\n    return bump\n` },
  { rule: "PY-TRUTH:3", name: "reading a module value without claiming it is not this rule", expect: "silent",
    code: `LIMIT = 10\n\n\ndef under(n):\n    return n < LIMIT\n` },
  { rule: "PY-TRUTH:3", name: "returning the new value is the shape the rule wants", expect: "silent",
    code: `def bump(count):\n    return count + 1\n` },
  { rule: "PY-TRUTH:3", name: "state held on an object is state with an owner", expect: "silent",
    code: `class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def bump(self):\n        self.count += 1\n` },
];
