export type PythonCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly file?: string;
};

export const PYTHON_CASES: readonly PythonCase[] = [
  { rule: "PY-ERROR:1", name: "a bare except swallowing everything", expect: "fires",
    code: `def f(p):\n    try:\n        return open(p).read()\n    except:\n        return ""\n` },
  { rule: "PY-ERROR:1", name: "an except whose body is pass", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        pass\n` },
  { rule: "PY-ERROR:1", name: "an except that does nothing by ellipsis", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        ...\n` },
  { rule: "PY-ERROR:1", name: "catching everything and doing nothing", expect: "fires",
    code: `def f(p):\n    try:\n        open(p)\n    except Exception:\n        pass\n` },
  { rule: "PY-ERROR:1", name: "a bare except is still bare when its body works", expect: "fires",
    code: `import logging\n\n\ndef f(p):\n    try:\n        open(p)\n    except:\n        logging.warning("could not open")\n` },
  { rule: "PY-ERROR:1", name: "logged and recovered from in the open", expect: "silent",
    code: `import logging\n\n\ndef f(p):\n    try:\n        open(p)\n    except OSError:\n        logging.warning("could not open %s", p)\n` },
  { rule: "PY-ERROR:1", name: "re-raised", expect: "silent",
    code: `def f(p):\n    try:\n        open(p)\n    except OSError:\n        raise\n` },
  { rule: "PY-ERROR:1", name: "re-raised as something named, keeping the cause", expect: "silent",
    code: `class Missing(Exception):\n    pass\n\n\ndef f(p):\n    try:\n        open(p)\n    except OSError as error:\n        raise Missing(p) from error\n` },
  { rule: "PY-ERROR:1", name: "suppress names what is ignored, which pass never does", expect: "silent",
    code: `from contextlib import suppress\n\n\ndef f(p):\n    with suppress(FileNotFoundError):\n        open(p)\n` },
  { rule: "PY-ERROR:1", name: "a class body of pass is not an except", expect: "silent",
    code: `class Missing(Exception):\n    pass\n` },
  { rule: "PY-ERROR:1", name: "a function body of pass is not an except", expect: "silent",
    code: `def later():\n    pass\n` },
  { rule: "PY-ERROR:1", name: "a try with no except at all", expect: "silent",
    code: `def f(p):\n    try:\n        open(p)\n    finally:\n        print("done")\n` },
  { rule: "PY-TRUTH:1", name: "an empty list as a default", expect: "fires",
    code: `def add(item, items=[]):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "an empty dict as a default", expect: "fires",
    code: `def add(key, seen={}):\n    seen[key] = True\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a set built by calling set()", expect: "fires",
    code: `def add(item, seen=set()):\n    seen.add(item)\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a list built by calling list()", expect: "fires",
    code: `def add(item, items=list()):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a method argument is no different", expect: "fires",
    code: `class Basket:\n    def add(self, item, items=[]):\n        items.append(item)\n        return items\n` },
  { rule: "PY-TRUTH:1", name: "a keyword-only argument is no different", expect: "fires",
    code: `def add(item, *, items=[]):\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a set written out in full", expect: "fires",
    code: `def add(item, seen={1, 2}):\n    seen.add(item)\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "None is the legal spelling", expect: "silent",
    code: `def add(item, items=None):\n    items = [] if items is None else items\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a tuple cannot be changed, so it is safe to share", expect: "silent",
    code: `def name(names=()):\n    return names\n` },
  { rule: "PY-TRUTH:1", name: "numbers and text cannot be changed either", expect: "silent",
    code: `def page(size=20, sort=""):\n    return size, sort\n` },
  { rule: "PY-TRUTH:1", name: "frozenset cannot be changed", expect: "silent",
    code: `def add(seen=frozenset()):\n    return seen\n` },
  { rule: "PY-TRUTH:1", name: "a list built inside the body is a new one each call", expect: "silent",
    code: `def add(item):\n    items = []\n    items.append(item)\n    return items\n` },
  { rule: "PY-TRUTH:1", name: "a name as a default is not a container this rule can see", expect: "silent",
    code: `EMPTY = ()\n\n\ndef add(names=EMPTY):\n    return names\n` },
  { rule: "PY-TRUTH:2", name: "a check on data written as an assert", expect: "fires",
    code: `def charge(amount):\n    assert amount > 0, "amount must be positive"\n    return amount\n` },
  { rule: "PY-TRUTH:2", name: "an assert narrowing a type", expect: "fires",
    code: `def read(proc):\n    assert proc.stdout is not None\n    return proc.stdout.read()\n` },
  { rule: "PY-TRUTH:2", name: "an internal invariant is still deleted by -O", expect: "fires",
    code: `def step(depth):\n    assert depth >= 0\n    return depth\n` },
  { rule: "PY-TRUTH:2", name: "a file named for tests is where assert belongs", expect: "silent",
    file: "test_charge.py",
    code: `def test_charge():\n    assert 1 + 1 == 2\n` },
  { rule: "PY-TRUTH:2", name: "a file ending in _test is the same", expect: "silent",
    file: "charge_test.py",
    code: `def test_charge():\n    assert 1 + 1 == 2\n` },
  { rule: "PY-TRUTH:2", name: "anything under a tests folder is the same", expect: "silent",
    file: "tests/checks.py",
    code: `def check():\n    assert 1 + 1 == 2\n` },
  { rule: "PY-TRUTH:2", name: "conftest is part of the test machinery", expect: "silent",
    file: "conftest.py",
    code: `def pytest_configure(config):\n    assert config is not None\n` },
  { rule: "PY-TRUTH:2", name: "raising is the legal spelling and survives -O", expect: "silent",
    code: `def charge(amount):\n    if amount <= 0:\n        raise ValueError("amount must be positive")\n    return amount\n` },
  { rule: "PY-TRUTH:2", name: "the word assert inside a name is not a statement", expect: "silent",
    code: `def assert_positive(amount):\n    if amount <= 0:\n        raise ValueError("no")\n    return amount\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with None", expect: "fires",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        return None\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with an empty list", expect: "fires",
    code: `def rows(path):\n    try:\n        return open(path).readlines()\n    except OSError:\n        return []\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with an empty string", expect: "fires",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        return ""\n` },
  { rule: "PY-ERROR:2", name: "answering a failure with a zero", expect: "fires",
    code: `def size(path):\n    try:\n        return len(open(path).read())\n    except OSError:\n        return 0\n` },
  { rule: "PY-ERROR:2", name: "a bare return is None wearing a shorter name", expect: "fires",
    code: `def read(path):\n    try:\n        return open(path).read()\n    except OSError:\n        return\n` },
  { rule: "PY-ERROR:2", name: "answering with an empty dict", expect: "fires",
    code: `def held(path):\n    try:\n        return {"text": open(path).read()}\n    except OSError:\n        return {}\n` },
  { rule: "PY-ERROR:2", name: "re-raising says the failure happened", expect: "silent",
    code: `class Missing(Exception):\n    pass\n\n\ndef read(path):\n    try:\n        return open(path).read()\n    except OSError as error:\n        raise Missing(path) from error\n` },
  { rule: "PY-ERROR:2", name: "a handler that uses the error is doing something with it", expect: "silent",
    code: `import logging\n\n\ndef read(path):\n    try:\n        return open(path).read()\n    except OSError as error:\n        logging.warning("could not read %s: %s", path, error)\n        return None\n` },
  { rule: "PY-ERROR:2", name: "the same answer the try already gives is not made up", expect: "silent",
    code: `def held(flag):\n    try:\n        return None\n    except OSError:\n        return None\n` },
  { rule: "PY-ERROR:2", name: "returning a real value from the handler is not a fabrication", expect: "silent",
    code: `def read(path, fallback):\n    try:\n        return open(path).read()\n    except OSError:\n        return fallback.read()\n` },
  { rule: "PY-TYPE:1", name: "silencing the checker on a line", expect: "fires",
    code: `def total(rows):\n    return sum(rows)  # type: ignore\n` },
  { rule: "PY-TYPE:1", name: "silencing one named complaint is still silencing it", expect: "fires",
    code: `def total(rows):\n    return sum(rows)  # type: ignore[arg-type]\n` },
  { rule: "PY-TYPE:1", name: "turning the checker off for a whole file", expect: "fires",
    code: `# mypy: ignore-errors\n\n\ndef total(rows):\n    return sum(rows)\n` },
  { rule: "PY-TYPE:1", name: "an old-style type comment says what a thing is", expect: "silent",
    code: `def total(rows):\n    count = 0  # type: int\n    return count\n` },
  { rule: "PY-TYPE:1", name: "prose that mentions the marker is not the marker", expect: "silent",
    code: `def total(rows):\n    # we should never need a type: ignore in here\n    return sum(rows)\n` },
  { rule: "PY-TYPE:1", name: "an annotation is the honest way to say it", expect: "silent",
    code: `def total(rows: list[int]) -> int:\n    return sum(rows)\n` },
  { rule: "PY-TYPE:1", name: "a string that happens to contain the words", expect: "silent",
    code: `HELP = "pass type: ignore to skip"\n` },
  { rule: "PY-LAYER:1", name: "a star import from a module", expect: "fires",
    code: `from os.path import *\n\n\ndef where(p):\n    return join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "a star import from a package beside it", expect: "fires",
    code: `from .models import *\n\n\ndef held():\n    return Order\n` },
  { rule: "PY-LAYER:1", name: "naming what you take says where it came from", expect: "silent",
    code: `from os.path import join\n\n\ndef where(p):\n    return join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "importing the module keeps the name on it", expect: "silent",
    code: `import os.path\n\n\ndef where(p):\n    return os.path.join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "renaming one name is not taking all of them", expect: "silent",
    code: `from os import path as here\n\n\ndef where(p):\n    return here.join(p, "x")\n` },
  { rule: "PY-LAYER:1", name: "a multiplication is not an import", expect: "silent",
    code: `def area(w, h):\n    return w * h\n` },
];
