export type ReportCase = {
  readonly name: string;
  readonly said: string;
  readonly theirs: readonly string[];
  readonly expect: "refused" | "passes";
  readonly stops: readonly string[];
};

const NOBODY: readonly string[] = [];

export const REPORT_CASES: readonly ReportCase[] = [
  { name: "control: a name written the way code writes one", expect: "refused",
    said: "I tried changing acmeBillingGateway to throw and the rule still fired.",
    theirs: NOBODY, stops: ["acmeBillingGateway"] },
  { name: "an underscore is how code joins two words", expect: "refused",
    said: "The tenant_ledger table is read before the rule looks at it.",
    theirs: NOBODY, stops: ["tenant_ledger"] },
  { name: "a capital in the middle of a sentence is a name", expect: "refused",
    said: "The rule fired while the agent was fixing the Contoso importer.",
    theirs: NOBODY, stops: ["Contoso"] },
  { name: "a word all in capitals is a name too", expect: "refused",
    said: "The gate named a line in the ACME module.",
    theirs: NOBODY, stops: ["ACME"] },
  { name: "a digit inside a word is a name or a version of one", expect: "refused",
    said: "It happened in the ledger2 package.",
    theirs: NOBODY, stops: ["ledger2"] },
  { name: "a path says where things are kept", expect: "refused",
    said: "It fired in crates/ledger/build.rs on the second line.",
    theirs: NOBODY, stops: ["crates/ledger/build.rs"] },
  { name: "a file name is a path one folder long", expect: "refused",
    said: "It fired in ledger.rs and nowhere else.",
    theirs: NOBODY, stops: ["ledger.rs"] },
  { name: "an address on the web", expect: "refused",
    said: "The case is written up at https://tracker.example/t/41 for anyone to read.",
    theirs: NOBODY, stops: ["https://tracker.example/t/41"] },
  { name: "an address for a person", expect: "refused",
    said: "Ask sam@contoso.example about the caller.",
    theirs: NOBODY, stops: ["sam@contoso.example"] },
  { name: "a call pasted in from the code", expect: "refused",
    said: "Calling settle(order) returns a list and the rule calls that a made-up value.",
    theirs: NOBODY, stops: ["settle(order)"] },
  { name: "a long number reads like a ticket or an account", expect: "refused",
    said: "The case is ticket 884213 in the tracker.",
    theirs: NOBODY, stops: ["884213"] },
  { name: "this project's own name, however plainly it is written", expect: "refused",
    said: "The ledgerworks build was blocked by the rule.",
    theirs: ["ledgerworks"], stops: ["ledgerworks"] },
  { name: "this project's own name inside a longer word", expect: "refused",
    said: "The ledgerworks-api build was blocked by the rule.",
    theirs: ["ledgerworks"], stops: ["ledgerworks-api"] },
  { name: "the project's name is caught in any letter case", expect: "refused",
    said: "Ledgerworks was blocked by the rule.",
    theirs: ["ledgerworks"], stops: ["Ledgerworks"] },
  { name: "a commit id is somebody's history", expect: "refused",
    said: "It has been wrong since 92164f9 went in.",
    theirs: NOBODY, stops: ["92164f9"] },
  { name: "a name joined to a plain word by a hyphen is still a name", expect: "refused",
    said: "It is a Windows-only failure.",
    theirs: NOBODY, stops: ["Windows-only"] },
  { name: "a letter outside a to z cannot be checked, so the report is written in plain English", expect: "refused",
    said: "Regeln slog till på en rad som är korrekt.",
    theirs: NOBODY, stops: ["på", "är"] },
  { name: "a product's name is a name", expect: "refused",
    said: "The rule fired in a Next.js page.",
    theirs: NOBODY, stops: ["Next.js"] },
  { name: "a file name that begins with a number is still a path", expect: "refused",
    said: "The rule fired on 0007-use-postgres-for-tenant-ledger-storage-now.md and the code is fine.",
    theirs: NOBODY, stops: ["0007-use-postgres-for-tenant-ledger-storage-now.md"] },
  { name: "a name in another alphabet is a name nobody here can check", expect: "refused",
    said: "The rule fired in the Ромашка модуль for one customer.",
    theirs: NOBODY, stops: ["Ромашка", "модуль"] },
  { name: "a name in a script that has no capitals", expect: "refused",
    said: "It should have stayed silent for 山田商店 as well.",
    theirs: NOBODY, stops: ["山田商店"] },
  { name: "one letter from another alphabet is still a letter nobody here can check", expect: "refused",
    said: "The field named 山 was the one it fired on.",
    theirs: NOBODY, stops: ["山"] },
  { name: "an address on a network is an address", expect: "refused",
    said: "The hook waited on 10.20.30.40 and then on 10.0.0.5:8443 for a minute.",
    theirs: NOBODY, stops: ["10.20.30.40", "10.0.0.5:8443"] },
  { name: "digits in groups read like a telephone, a card or an account", expect: "refused",
    said: "The record held 555-123-4567 and 4111-1111-1111-1111 and the rule printed both.",
    theirs: NOBODY, stops: ["555-123-4567", "4111-1111-1111-1111"] },
  { name: "a name with a number in front of it is still a name", expect: "refused",
    said: "It happened in the 7acme build and again in 42northwind.",
    theirs: NOBODY, stops: ["7acme", "42northwind"] },
  { name: "a capital after a colon opens no sentence", expect: "refused",
    said: "It fired for one customer: Northwind and nobody else.",
    theirs: NOBODY, stops: ["Northwind"] },
  { name: "a capital after an abbreviation opens no sentence", expect: "refused",
    said: "Some customers, e.g. Contoso, never saw it.",
    theirs: NOBODY, stops: ["Contoso"] },
  { name: "a capital that opens a line opens no sentence", expect: "refused",
    said: "The rule fired for\nTailspin and for nobody else.",
    theirs: NOBODY, stops: ["Tailspin"] },

  { name: "plain words about a rule", expect: "passes",
    said: "The rule fired on a return inside a catch that the caller already observes.",
    theirs: NOBODY, stops: [] },
  { name: "looper's own rule ids are looper's words", expect: "passes",
    said: "TS-ERROR:3 fired on a line that TS-TRUTH:4 already governs.",
    theirs: NOBODY, stops: [] },
  { name: "looper's own names for its parts, written as code writes them", expect: "passes",
    said: "The PostToolUse hook printed nothing and the doctrine tool said the rule set was missing.",
    theirs: NOBODY, stops: [] },
  { name: "a capital that opens a sentence is only a capital", expect: "passes",
    said: "Nothing was printed. The hook exited and the edit went through. Then the commit was refused.",
    theirs: NOBODY, stops: [] },
  { name: "numbers, dates and sizes are not names", expect: "passes",
    said: "It took 45 seconds on 2026-10-01 over 1,932 files, in a 9,580-character turn, 3 times out of 4.",
    theirs: NOBODY, stops: [] },
  { name: "a language looper itself names", expect: "passes",
    said: "The rule reads TypeScript and Python the same way and Rust differently.",
    theirs: NOBODY, stops: [] },
  { name: "a file in looper's own tree", expect: "passes",
    said: "The decision is taken in src/law/ts/parse.ts before any rule runs.",
    theirs: NOBODY, stops: [] },
  { name: "a possessive and a quoted word", expect: "passes",
    said: "looper's hook said 'passing' and the agent's turn went on as if it had been judged.",
    theirs: NOBODY, stops: [] },
  { name: "the sentence issue #60 could not write", expect: "passes",
    said: "The gate named a line where TRUTH does not apply.",
    theirs: NOBODY, stops: [] },
  { name: "the sentence finding 61 could not write", expect: "passes",
    said: "the suggested spellings do not apply here",
    theirs: NOBODY, stops: [] },
  { name: "a word joined by a hyphen is still plain words", expect: "passes",
    said: "The rule is right about a hand-written check and wrong about a built-in one.",
    theirs: NOBODY, stops: [] },
  { name: "a number in brackets and a reference to an issue are numbers", expect: "passes",
    said: "It happened 3 times (157 files) and is the same fault as #185.",
    theirs: NOBODY, stops: [] },
  { name: "a word in brackets is still a word", expect: "passes",
    said: "The second spelling (the legal one) was refused too.",
    theirs: NOBODY, stops: [] },
  { name: "a contraction is not a name", expect: "passes",
    said: "The hook passed and I'd expect it to say so, because I've seen it fail twice.",
    theirs: NOBODY, stops: [] },
  { name: "an abbreviation written with dots", expect: "passes",
    said: "Some checks, e.g. the slow ones, never ran.",
    theirs: NOBODY, stops: [] },
  { name: "a size written with a sign in front", expect: "passes",
    said: "The hook took ≥60s the first time and ~90s the second.",
    theirs: NOBODY, stops: [] },
  { name: "a file looper ships at its own root", expect: "passes",
    said: "The gate runs on every edit, and README.md says so.",
    theirs: NOBODY, stops: [] },
  { name: "a dash between two halves of a sentence", expect: "passes",
    said: "The rule fired — and the line it named holds nothing.",
    theirs: NOBODY, stops: [] },
  { name: "a dash with no space around it still divides two words", expect: "passes",
    said: "The rule fired—and the line it named holds nothing.",
    theirs: NOBODY, stops: [] },
  { name: "words joined by hyphens are judged one by one", expect: "passes",
    said: "The Rust-to-TypeScript rule fired on a 7-to-40-character token.",
    theirs: NOBODY, stops: [] },
  { name: "a version with a plus and a size with a capital unit", expect: "passes",
    said: "It needs Node 22.18+ and the picture was 4K wide.",
    theirs: NOBODY, stops: [] },
  { name: "a project whose name is a word looper uses cannot stop that word", expect: "passes",
    said: "The rule fired in a test and the report says so.",
    theirs: ["test"], stops: [] },
  { name: "a version in three parts, a time of day and a share", expect: "passes",
    said: "It needs Node 22.18.0, it ran at 14:05 and it passed 3/4 of the time.",
    theirs: NOBODY, stops: [] },
  { name: "a count with a unit written against it", expect: "passes",
    said: "It took 120ms the first time, 30s the second and 5min the third, on a 64-bit machine with 16GB.",
    theirs: NOBODY, stops: [] },
  { name: "a range of lines and a size in two numbers", expect: "passes",
    said: "It named lines 12-18 of a picture 1920x1080 wide, 2.5-second pauses apart.",
    theirs: NOBODY, stops: [] },
  { name: "a sentence that opens after a question or an exclamation", expect: "passes",
    said: "Why did it pass? Nothing was checked! Then the commit was refused.",
    theirs: NOBODY, stops: [] },
];
