export type RustCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly upstream?: string;
};

export const RUST_CASES: readonly RustCase[] = [
  { rule: "RUST-ERROR:1", name: "unwrap on a Result", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { v.unwrap() }` },
  { rule: "RUST-ERROR:1", name: "the match arm that names the failure is lawful", expect: "silent",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { match v { Ok(n) => n, Err(e) => e } }` },
  { rule: "RUST-ERROR:2", name: "the payload thrown away", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { match v { Ok(n) => n, Err(_) => 0 } }` },
  { rule: "RUST-ERROR:3", name: "an Err arm answering with a made-up value", expect: "fires",
    code: `pub fn f(v: Result<u8, String>) -> u8 { match v { Ok(n) => n, Err(e) => { let _ = e; 0 } } }` },
  { rule: "RUST-ERROR:7", name: "catch_unwind outside the boundary", expect: "fires",
    code: `pub fn f() { let _ = std::panic::catch_unwind(|| ()); }` },
  { rule: "RUST-TYPE:1", name: "an error type that says nothing", expect: "fires",
    code: `pub fn f() -> Result<u8, String> { Ok(1) }` },
  { rule: "RUST-TYPE:4", name: "an as cast", expect: "fires",
    code: `pub fn f(n: u32) -> u8 { n as u8 }` },
  { rule: "RUST-TYPE:4", name: "a use renaming an import is not a cast", expect: "silent",
    code: `use std::collections::HashMap as Map;\npub fn f() -> Map<u8, u8> { Map::new() }` },
  { rule: "RUST-TYPE:5", name: "saturating arithmetic", expect: "fires",
    code: `pub fn f(a: u8) -> u8 { a.saturating_sub(1) }` },
  { rule: "RUST-TYPE:5", name: "a function whose own name contains one is not one", expect: "silent",
    code: `pub fn my_saturating_sub(a: u8) -> u8 { a - 1 }` },
  { rule: "RUST-DEAD:1", name: "an allow that hides dead code", expect: "fires",
    code: `#[allow(dead_code)]\npub fn f() {}` },
  { rule: "RUST-DEAD:1", name: "an allow about something else is not one", expect: "silent",
    code: `#[allow(clippy::needless_return)]\npub fn f() {}` },
  { rule: "RUST-DEAD:2", name: "a comment", expect: "fires",
    code: `// this is a comment\npub fn f() {}` },
  { rule: "RUST-DEAD:2", name: "a comment inside a string is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { "// not a comment" }` },
  { rule: "RUST-DEAD:2", name: "a url in a string is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { "https://example.invalid/x" }` },
  { rule: "RUST-DEAD:2", name: "a raw string holding a comment is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { r#"// raw"# }` },
  { rule: "RUST-DEAD:3", name: "todo!", expect: "fires",
    code: `pub fn f() { todo!() }` },
  { rule: "RUST-DEAD:3", name: "todo as an identifier is not the macro", expect: "silent",
    code: `pub fn f() -> u8 { let todo = 1; todo }` },
  { rule: "RUST-DEAD:4", name: "a glob import", expect: "fires",
    code: `use std::collections::*;\npub fn f() {}` },
  { rule: "RUST-TRUTH:2", name: "reading the environment", expect: "fires",
    code: `pub fn f() -> Result<String, std::env::VarError> { std::env::var("HOME") }` },
  { rule: "RUST-LOG:1", name: "println outside the entry point", expect: "fires",
    code: `pub fn f() { println!("hello"); }` },
  { rule: "RUST-LOG:2", name: "taking the output handle", expect: "fires",
    code: `pub fn f() { let _ = std::io::stdout(); }` },
  { rule: "RUST-TESTS:1", name: "a test module under src", expect: "fires",
    code: `#[cfg(test)]\nmod tests {}` },
  { rule: "RUST-ERROR:9", name: "a file that is not Rust at all", expect: "fires",
    code: `this is not rust {{{` },

  { rule: "RUST-TYPE:4", name: "a cast inside a macro argument", expect: "fires",
    upstream: "the four rules below match on typed syntax, and a macro's arguments never become that",
    code: `pub fn f(n: u32) { println!("{}", n as u8); }` },
  { rule: "RUST-TRUTH:2", name: "an environment read inside a macro argument", expect: "fires",
    upstream: "same shape as the cast above",
    code: `pub fn f() { println!("{:?}", std::env::var("HOME")); }` },
  { rule: "RUST-DEAD:3", name: "todo! inside a macro argument", expect: "fires",
    upstream: "same shape as the cast above",
    code: `pub fn f() { println!("{}", todo!()); }` },
];
