export type Place = "tests" | "examples";

export type RustCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly notFixedYet?: string;
  readonly place?: Place;
};

export const RUST_CASES: readonly RustCase[] = [
  { rule: "RUST-ERROR:1", name: "unwrap on a Result", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { v.unwrap() }` },
  { rule: "RUST-ERROR:1", name: "the match arm that names the failure is lawful", expect: "silent",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { match v { Ok(n) => n, Err(e) => e } }` },
  { rule: "RUST-ERROR:2", name: "the payload thrown away", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { match v { Ok(n) => n, Err(_) => 0 } }` },
  { rule: "RUST-ERROR:3", name: "an Err arm answering with a made-up value", expect: "fires",
    code: `pub fn f(v: Result<u8, String>) -> u8 { match v { Ok(n) => n, Err(e) => { let _ = e; 0 } } }` },
  { rule: "RUST-ERROR:7", name: "catch_unwind outside the boundary", expect: "fires",
    code: `pub fn f() { let _ = std::panic::catch_unwind(|| ()); }` },
  { rule: "RUST-TYPE:1", name: "an error type that says nothing", expect: "fires",
    code: `pub fn f() -> Result<u8, String> { Ok(1) }` },
  { rule: "RUST-TYPE:4", name: "an as cast", expect: "fires",
    code: `pub fn f(n: u32) -> u8 { n as u8 }` },
  { rule: "RUST-TYPE:4", name: "a use renaming an import is not a cast", expect: "silent",
    code: `use std::collections::HashMap as Map;\npub fn f() -> Map<u8, u8> { Map::new() }` },
  { rule: "RUST-TYPE:5", name: "saturating arithmetic", expect: "fires",
    code: `pub fn f(a: u8) -> u8 { a.saturating_sub(1) }` },
  { rule: "RUST-TYPE:5", name: "a function whose own name contains one is not one", expect: "silent",
    code: `pub fn my_saturating_sub(a: u8) -> u8 { a - 1 }` },
  { rule: "RUST-DEAD:1", name: "an allow that hides dead code", expect: "fires",
    code: `#[allow(dead_code)]\npub fn f() {}` },
  { rule: "RUST-DEAD:1", name: "an allow about something else is not one", expect: "silent",
    code: `#[allow(clippy::needless_return)]\npub fn f() {}` },
  { rule: "RUST-DEAD:2", name: "a comment", expect: "fires",
    code: `// this is a comment\npub fn f() {}` },
  { rule: "RUST-DEAD:2", name: "a comment inside a string is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { "// not a comment" }` },
  { rule: "RUST-DEAD:2", name: "a url in a string is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { "https://example.invalid/x" }` },
  { rule: "RUST-DEAD:2", name: "a raw string holding a comment is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { r#"// raw"# }` },
  { rule: "RUST-DEAD:3", name: "todo!", expect: "fires",
    code: `pub fn f() { todo!() }` },
  { rule: "RUST-DEAD:3", name: "todo as an identifier is not the macro", expect: "silent",
    code: `pub fn f() -> u8 { let todo = 1; todo }` },
  { rule: "RUST-DEAD:4", name: "a glob import", expect: "fires",
    code: `use std::collections::*;\npub fn f() {}` },
  { rule: "RUST-TRUTH:2", name: "reading the environment", expect: "fires",
    code: `pub fn f() -> Result<String, std::env::VarError> { std::env::var("HOME") }` },
  { rule: "RUST-LOG:1", name: "println outside the entry point", expect: "fires",
    code: `pub fn f() { println!("hello"); }` },
  { rule: "RUST-LOG:2", name: "taking the output handle", expect: "fires",
    code: `pub fn f() { let _ = std::io::stdout(); }` },
  { rule: "RUST-LOG:3", name: "control: a captured identifier in the message", expect: "fires",
    code: `pub fn f(id: u64) { tracing::info!("saved {id}"); }` },
  { rule: "RUST-LOG:3", name: "a positional argument is the same offence", expect: "fires",
    code: `pub fn f(id: u64) { tracing::info!("saved {}", id); }` },
  { rule: "RUST-LOG:3", name: "every level is judged, not only info", expect: "fires",
    code: `pub fn f(id: u64) { tracing::warn!("retrying {id}"); }` },
  { rule: "RUST-LOG:3", name: "a field beside a constant message is the shape that works", expect: "silent",
    code: `pub fn f(id: u64) { tracing::info!(order = %id, "saved"); }` },
  { rule: "RUST-LOG:3", name: "a message with nothing in it", expect: "silent",
    code: `pub fn f() { tracing::info!("saved"); }` },
  { rule: "RUST-LOG:3", name: "an escaped brace is a brace, not a value", expect: "silent",
    code: `pub fn f() { tracing::info!("a {{literal}} brace"); }` },
  { rule: "RUST-TESTS:1", name: "a test module under src", expect: "fires",
    code: `#[cfg(test)]\nmod tests {}` },
  { rule: "RUST-ERROR:1", name: "comparing against another type's None is not Option::None", expect: "silent",
    code: `pub enum Delimiter { None, Brace }\npub fn f(d: Delimiter) -> bool { matches!(d, Delimiter::None) }` },
  { rule: "RUST-ERROR:1", name: "comparing against Option::None is still caught", expect: "fires",
    code: `pub fn f(v: Option<u8>) -> bool { v == None }` },
  { rule: "RUST-ERROR:1", name: "the fallible family reached as a path, not a method", expect: "fires",
    code: `pub fn f(v: Option<u8>) -> u8 { let g = Option::unwrap; g(v) }` },
  { rule: "RUST-ERROR:3", name: "an Err arm answering with an empty string built the long way", expect: "fires",
    code: `pub fn f(v: Result<String, u8>) -> String { match v { Ok(s) => s, Err(e) => { let _ = e; "".to_string() } } }` },
  { rule: "RUST-DEAD:3", name: "a panic that says the work is not done", expect: "fires",
    code: `pub fn f() { panic!("not implemented yet") }` },
  { rule: "RUST-DEAD:3", name: "a panic that says something real is the crash door", expect: "silent",
    code: `pub fn f(n: u8) { if n == 0 { panic!("the config named no port") } }` },
  { rule: "RUST-TRUTH:2", name: "the environment reached through a subprocess", expect: "fires",
    code: `pub fn f() -> std::io::Result<std::process::Output> { std::process::Command::new("printenv").output() }` },
  { rule: "RUST-TRUTH:2", name: "running an ordinary program is not reading the environment", expect: "silent",
    code: `pub fn f() -> std::io::Result<std::process::Output> { std::process::Command::new("git").output() }` },
  { rule: "RUST-TRUTH:2", name: "the same read done at compile time", expect: "fires",
    code: `pub const HOME: &str = env!("HOME");` },
  { rule: "RUST-TRUTH:2", name: "a key cargo sets itself is still a setting under src", expect: "fires",
    code: `pub const HERE: &str = env!("CARGO_MANIFEST_DIR");` },
  { rule: "RUST-TRUTH:2", name: "and inside a macro argument under src", expect: "fires",
    code: `pub fn f() -> String { format!("{}", env!("CARGO_PKG_NAME")) }` },
  { rule: "RUST-ERROR:9", name: "a file that is not Rust at all", expect: "fires",
    code: `this is not rust {{{` },

  { rule: "RUST-TYPE:4", name: "a cast inside a macro argument", expect: "fires",
    code: `pub fn f(n: u32) { println!("{}", n as u8); }` },
  { rule: "RUST-TRUTH:2", name: "an environment read inside a macro argument", expect: "fires",
    code: `pub fn f() { println!("{:?}", std::env::var("HOME")); }` },
  { rule: "RUST-DEAD:3", name: "todo! inside a macro argument", expect: "fires",
    code: `pub fn f() { println!("{}", todo!()); }` },
  { rule: "RUST-LAYER:2", name: "a crate path inside a macro argument", expect: "fires",
    code: `pub fn f() { println!("{:?}", crate::f); }` },
  { rule: "RUST-LAYER:2", name: "a use statement is where a crate path belongs", expect: "silent",
    code: `use crate::f as g;\npub fn h() -> u8 { let _ = g; 1 }` },
  { rule: "RUST-TYPE:4", name: "a rename inside a macro body is not a cast", expect: "silent",
    code: `macro_rules! bring { () => { use std::collections::HashMap as Map; }; }\npub fn f() { bring!(); }` },

  { rule: "RUST-TYPE:4", name: "a float cast inside a macro argument is still a cast", expect: "fires",
    code: `pub fn f(n: u64) { println!("{}", n as f64); }` },
  { rule: "RUST-TYPE:4", name: "a query macro's column type override is not a numeric cast", expect: "silent",
    code: `pub fn f(role: &str) { let _ = sqlx::query!("insert $1", role as &str); }` },
  { rule: "RUST-TYPE:4", name: "an override to an Option type inside a macro is not a numeric cast", expect: "silent",
    code: `pub fn f(plan: Option<&str>) { let _ = sqlx::query!("insert $1", plan as Option<&str>); }` },
  { rule: "RUST-TYPE:4", name: "an override to a named type inside a macro is not a numeric cast", expect: "silent",
    code: `pub struct Role;\npub fn f(role: Role) { let _ = sqlx::query!("insert $1", role as Role); }` },
  { rule: "RUST-TYPE:4", name: "a pointer cast written as Rust, not as macro tokens, is still a cast", expect: "fires",
    code: `pub fn f(x: &u8) -> *const u8 { x as *const u8 }` },

  { rule: "RUST-TYPE:4", name: "a cast to an inferred type inside a macro hides its target and is still a cast", expect: "fires",
    code: `pub fn f(n: u64) { println!("{}", n as _); }` },
  { rule: "RUST-TYPE:4", name: "a pointer cast inside a macro argument is still a cast", expect: "fires",
    code: `pub fn f(x: &u8) { println!("{:?}", x as *const u8); }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that logs then calls a second route", expect: "fires",
    code: `pub fn read(p: &str) -> u8 { match fast(p) { Ok(n) => n, Err(cause) => { tracing::warn!(?cause, "unread"); slow(p) } } }\nfn fast(_p: &str) -> Result<u8, u8> { Ok(1) }\nfn slow(_p: &str) -> u8 { 2 }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that calls a method route", expect: "fires",
    code: `pub struct S;\nimpl S { pub fn read(&self, p: &str) -> u8 { match fast(p) { Ok(n) => n, Err(cause) => { tracing::warn!(?cause, "unread"); self.slow(p) } } }\n fn slow(&self, _p: &str) -> u8 { 2 } }\nfn fast(_p: &str) -> Result<u8, u8> { Ok(1) }` },
  { rule: "RUST-TRUTH:3", name: "a let else that calls a second route is an absence with an answer", expect: "silent",
    code: `pub fn read(fast: Option<u8>) -> u8 { let Some(n) = fast else { return slow(); }; n }\nfn slow() -> u8 { 2 }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that propagates is the shape the rule wants", expect: "silent",
    code: `pub struct Cause;\npub fn read(p: &str) -> Result<u8, Cause> { match fast(p) { Ok(n) => Ok(n), Err(cause) => Err(cause) } }\nfn fast(_p: &str) -> Result<u8, Cause> { Ok(1) }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that logs then names the absence", expect: "silent",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(p: &str) -> Held { match fast(p) { Ok(n) => Held::At(n), Err(cause) => { tracing::warn!(?cause, "unread"); Held::Absent } } }\nfn fast(_p: &str) -> Result<u8, u8> { Ok(1) }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that converts the cause it was handed", expect: "silent",
    code: `pub fn read(p: &str) -> String { match fast(p) { Ok(n) => n, Err(cause) => { tracing::warn!(?cause, "unread"); cause.to_string() } } }\nfn fast(_p: &str) -> Result<String, String> { Ok(String::new()) }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that crashes", expect: "silent",
    code: `pub fn read(p: &str) -> u8 { match fast(p) { Ok(n) => n, Err(cause) => panic!("unread {cause}") } }\nfn fast(_p: &str) -> Result<u8, u8> { Ok(1) }` },
  { rule: "RUST-TRUTH:3", name: "a let else that names the absence", expect: "silent",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(fast: Option<u8>) -> Held { let Some(n) = fast else { return Held::Absent; }; Held::At(n) }` },
  { rule: "RUST-TRUTH:3", name: "a let else that returns an error", expect: "silent",
    code: `pub struct Missing;\npub fn read(fast: Option<u8>) -> Result<u8, Missing> { let Some(n) = fast else { return Err(Missing); }; Ok(n) }` },
  { rule: "RUST-TRUTH:3", name: "a let else that builds a default with an associated function", expect: "silent",
    code: `pub fn refusal_of(said: Option<String>) -> String { let Some(said) = said else { return String::from("no reason given"); }; said }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm that converts a named constant into the answer", expect: "silent",
    code: `pub struct Code;\nimpl Code { pub fn into_response(self) -> u8 { 1 } }\npub const REFUSED: Code = Code;\npub fn read(p: &str) -> u8 { match fast(p) { Ok(n) => n, Err(cause) => { tracing::warn!(?cause, "unread"); REFUSED.into_response() } } }\nfn fast(_p: &str) -> Result<u8, u8> { Ok(1) }` },
  { rule: "RUST-TRUTH:3", name: "a let else answered by a helper that names the absence", expect: "silent",
    code: `pub struct Marks;\npub fn read(seen: Option<u8>) -> Marks { let Some(_n) = seen else { return nothing(); }; Marks }\nfn nothing() -> Marks { Marks }` },
  { rule: "RUST-TRUTH:3", name: "cfg twin bodies are a port, not a fallback", expect: "silent",
    code: `#[cfg(windows)]\npub fn now() -> u8 { 1 }\n#[cfg(unix)]\npub fn now() -> u8 { 2 }` },
  { rule: "RUST-TRUTH:3", name: "an Err arm answered by a helper that names the refusal", expect: "silent",
    code: `pub struct Refusal;\npub fn read(p: &str) -> Result<u8, Refusal> { match fast(p) { Ok(n) => Ok(n), Err(cause) => { tracing::warn!(?cause, "unread"); refused("the reader did not answer") } } }\nfn refused(_why: &str) -> Result<u8, Refusal> { Err(Refusal) }\nfn fast(_p: &str) -> Result<u8, Refusal> { Ok(1) }` },

  { rule: "RUST-TRUTH:1", name: "a None arm that answers with a made-up number", expect: "fires",
    code: `pub fn timeout(said: Option<u64>) -> u64 { match said { Some(t) => t, None => 30 } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that answers with an empty string", expect: "fires",
    code: `pub fn name(said: Option<&'static str>) -> &'static str { match said { Some(n) => n, None => "" } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that answers with an empty collection", expect: "fires",
    code: `pub fn rows(said: Option<Vec<u8>>) -> Vec<u8> { match said { Some(r) => r, None => Vec::new() } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that answers with the type's default", expect: "fires",
    code: `pub fn name(said: Option<String>) -> String { match said { Some(n) => n, None => Default::default() } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that answers with a constant", expect: "fires",
    code: `pub fn limit(said: Option<u64>) -> u64 { match said { Some(n) => n, None => u64::MAX } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that answers with a variant the present value could also be", expect: "fires",
    code: `pub enum Pace { Slow, Fast }\npub fn pace(said: Option<Pace>) -> Pace { match said { Some(p) => p, None => Pace::Slow } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that answers with a variant another arm also yields", expect: "fires",
    code: `pub enum Pace { Slow, Fast }\npub fn pace(said: Option<bool>) -> Pace { match said { Some(true) => Pace::Fast, Some(false) => Pace::Slow, None => Pace::Slow } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that fills the present variant with a made-up value", expect: "fires",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(fast: Option<u8>) -> Held { match fast { Some(n) => Held::At(n), None => Held::At(0) } }` },
  { rule: "RUST-TRUTH:1", name: "a variant names the absence only when every other arm visibly yields another one", expect: "fires",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(fast: Option<u8>) -> Held { match fast { Some(n) => decode(n), None => Held::Absent } }\nfn decode(n: u8) -> Held { Held::At(n) }` },
  { rule: "RUST-TRUTH:1", name: "a None arm shared with a present value is not a name for absence", expect: "fires",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(fast: Option<u8>) -> Held { match fast { Some(0) | None => Held::Absent, Some(n) => Held::At(n) } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that names the absence with the function's own variant", expect: "silent",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(fast: Option<u8>) -> Held { match fast { Some(n) => Held::At(n), None => Held::Absent } }` },
  { rule: "RUST-TRUTH:1", name: "the same absence named from a let else is judged alike", expect: "silent",
    code: `pub enum Held { Absent, At(u8) }\npub fn read(fast: Option<u8>) -> Held { let Some(n) = fast else { return Held::Absent; }; Held::At(n) }` },
  { rule: "RUST-TRUTH:1", name: "a query that may find no row names the absence inside Ok", expect: "silent",
    code: `pub struct Row;\npub struct Unread;\npub enum Found { Row(Row), Missing }\npub fn find(row: Result<Option<Row>, Unread>) -> Result<Found, Unread> { match row? { Some(r) => Ok(Found::Row(r)), None => Ok(Found::Missing) } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that logs and then names the absence", expect: "silent",
    code: `pub struct Row;\npub enum Found { Row(Row), Missing }\npub fn find(row: Option<Row>) -> Found { match row { Some(r) => Found::Row(r), None => { tracing::info!("no row"); Found::Missing } } }` },
  { rule: "RUST-TRUTH:1", name: "the absence named through Self", expect: "silent",
    code: `pub enum Held { Absent, At(u8) }\nimpl Held { pub fn of(fast: Option<u8>) -> Self { match fast { Some(n) => Self::At(n), None => Self::Absent } } }` },
  { rule: "RUST-TRUTH:1", name: "a variant that only absence produces names it, whatever the word", expect: "silent",
    code: `pub enum Pace { Slow, Steady, Fast }\npub fn pace(said: Option<bool>) -> Pace { match said { Some(true) => Pace::Fast, Some(false) => Pace::Slow, None => Pace::Steady } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that hands the absence on as None", expect: "silent",
    code: `pub fn next(at: Option<u64>) -> Option<u64> { match at { Some(n) => n.checked_add(1), None => None } }` },
  { rule: "RUST-TRUTH:1", name: "a None arm that hands the absence on inside Ok", expect: "silent",
    code: `pub struct Unread;\npub fn next(at: Result<Option<u64>, Unread>) -> Result<Option<u64>, Unread> { match at? { Some(n) => Ok(n.checked_add(1)), None => Ok(None) } }` },

  { rule: "RUST-ERROR:1", name: "expect under src is still refused", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { v.expect("a value") }` },
  { rule: "RUST-ERROR:1", name: "a fixture helper in a test file may expect: a failure there fails the test out loud", expect: "silent", place: "tests",
    code: `fn seven() -> u8 { "7".parse().expect("the fixture parses") }\n#[test]\nfn reads() { assert_eq!(seven(), 7); }` },
  { rule: "RUST-ERROR:1", name: "unwrap in a test helper is the same loud failure", expect: "silent", place: "tests",
    code: `pub fn seven() -> u8 { "7".parse().unwrap() }` },
  { rule: "RUST-ERROR:1", name: "unwrap_err in a test helper asserts the failure it expects", expect: "silent", place: "tests",
    code: `pub fn refusal() -> std::num::ParseIntError { "x".parse::<u8>().unwrap_err() }` },
  { rule: "RUST-ERROR:1", name: "expect inside an assertion in a test helper", expect: "silent", place: "tests",
    code: `pub fn check() { assert_eq!("7".parse::<u8>().expect("parses"), 7); }` },
  { rule: "RUST-ERROR:1", name: "unwrap_or in a test helper still answers a failure with a value", expect: "fires", place: "tests",
    code: `pub fn seven() -> u8 { "x".parse().unwrap_or(7) }` },
  { rule: "RUST-ERROR:1", name: "ok() in a test helper still throws the failure away", expect: "fires", place: "tests",
    code: `pub fn seven() -> Option<u8> { "7".parse().ok() }` },
  { rule: "RUST-ERROR:1", name: "is_ok in a test helper still reads the answer and drops the evidence", expect: "fires", place: "tests",
    code: `pub fn parses() -> bool { "7".parse::<u8>().is_ok() }` },
  { rule: "RUST-ERROR:1", name: "an example program is not a test, so its unwrap is still refused", expect: "fires", place: "examples",
    code: `fn main() -> std::process::ExitCode { let n: u8 = "7".parse().unwrap(); std::process::ExitCode::from(n) }` },

  { rule: "RUST-LOG:1", name: "an example program prints its own output", expect: "silent", place: "examples",
    code: `fn main() { println!("the example shows this"); }` },
  { rule: "RUST-LOG:1", name: "a test file is not a program start, so its helpers do not print", expect: "fires", place: "tests",
    code: `pub fn noise() { println!("noise"); }` },
  { rule: "RUST-ERROR:5", name: "an example program is a crate root and appoints its deputies", expect: "fires", place: "examples",
    code: `fn main() {}` },
  { rule: "RUST-ERROR:5", name: "an example that appoints them", expect: "silent", place: "examples",
    code: `#![deny(unused_must_use)]\n#![deny(for_loops_over_fallibles)]\n#![deny(dead_code)]\n#![deny(unused_variables)]\n#![deny(unused_assignments)]\nfn main() {}` },

  { rule: "RUST-ERROR:4", name: "a program start writes its failure to stderr and exits with failure", expect: "silent", place: "examples",
    code: `#[derive(Debug)]\npub struct Failed;\nfn run() -> Result<(), Failed> { Ok(()) }\nfn main() -> std::process::ExitCode { match run() { Ok(()) => std::process::ExitCode::SUCCESS, Err(failure) => { eprintln!("run: {failure:?}"); std::process::ExitCode::FAILURE } } }` },
  { rule: "RUST-ERROR:4", name: "the same arm in a library has written nothing down", expect: "fires",
    code: `#[derive(Debug)]\npub struct Failed;\nfn run() -> Result<(), Failed> { Ok(()) }\npub fn go() -> u8 { match run() { Ok(()) => 0, Err(failure) => { eprintln!("run: {failure:?}"); 1 } } }` },
  { rule: "RUST-ERROR:4", name: "a program start that prints something other than the failure has not written it down", expect: "fires", place: "examples",
    code: `#[derive(Debug)]\npub struct Failed;\nfn run() -> Result<(), Failed> { Ok(()) }\nfn main() -> std::process::ExitCode { match run() { Ok(()) => std::process::ExitCode::SUCCESS, Err(failure) => { eprintln!("it failed"); std::process::ExitCode::FAILURE } } }` },
  { rule: "RUST-ERROR:4", name: "a test lock taken back after another test panicked", expect: "silent", place: "tests",
    code: `use std::sync::{Mutex, MutexGuard};\nstatic IN_TURN: Mutex<()> = Mutex::new(());\npub fn turn() -> MutexGuard<'static, ()> { match IN_TURN.lock() { Ok(held) => held, Err(poisoned) => poisoned.into_inner() } }` },
  { rule: "RUST-ERROR:4", name: "a read lock taken back in a test", expect: "silent", place: "tests",
    code: `use std::sync::{RwLock, RwLockReadGuard};\nstatic SHARED: RwLock<u8> = RwLock::new(0);\npub fn look() -> RwLockReadGuard<'static, u8> { match SHARED.read() { Ok(seen) => seen, Err(poisoned) => poisoned.into_inner() } }` },
  { rule: "RUST-ERROR:4", name: "the same recovery in a library is still a judgment the arm must show", expect: "fires",
    code: `use std::sync::{Mutex, MutexGuard};\nstatic IN_TURN: Mutex<()> = Mutex::new(());\npub fn turn() -> MutexGuard<'static, ()> { match IN_TURN.lock() { Ok(held) => held, Err(poisoned) => poisoned.into_inner() } }` },
  { rule: "RUST-ERROR:4", name: "into_inner on something that is not a lock is not a lock taken back", expect: "fires", place: "tests",
    code: `pub struct Wrapped(pub u8);\nimpl Wrapped { pub fn into_inner(self) -> u8 { self.0 } }\npub fn read(v: Result<u8, Wrapped>) -> u8 { match v { Ok(n) => n, Err(w) => w.into_inner() } }` },
];
