export type RustCase = {
  readonly rule: string;
  readonly name: string;
  readonly code: string;
  readonly expect: "fires" | "silent";
  readonly notFixedYet?: string;
};

export const RUST_CASES: readonly RustCase[] = [
  { rule: "RUST-ERROR:1", name: "unwrap on a Result", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { v.unwrap() }` },
  { rule: "RUST-ERROR:1", name: "the match arm that names the failure is lawful", expect: "silent",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { match v { Ok(n) => n, Err(e) => e } }` },
  { rule: "RUST-ERROR:2", name: "the payload thrown away", expect: "fires",
    code: `pub fn f(v: Result<u8, u8>) -> u8 { match v { Ok(n) => n, Err(_) => 0 } }` },
  { rule: "RUST-ERROR:3", name: "an Err arm answering with a made-up value", expect: "fires",
    code: `pub fn f(v: Result<u8, String>) -> u8 { match v { Ok(n) => n, Err(e) => { let _ = e; 0 } } }` },
  { rule: "RUST-ERROR:7", name: "catch_unwind outside the boundary", expect: "fires",
    code: `pub fn f() { let _ = std::panic::catch_unwind(|| ()); }` },
  { rule: "RUST-TYPE:1", name: "an error type that says nothing", expect: "fires",
    code: `pub fn f() -> Result<u8, String> { Ok(1) }` },
  { rule: "RUST-TYPE:4", name: "an as cast", expect: "fires",
    code: `pub fn f(n: u32) -> u8 { n as u8 }` },
  { rule: "RUST-TYPE:4", name: "a use renaming an import is not a cast", expect: "silent",
    code: `use std::collections::HashMap as Map;\npub fn f() -> Map<u8, u8> { Map::new() }` },
  { rule: "RUST-TYPE:5", name: "saturating arithmetic", expect: "fires",
    code: `pub fn f(a: u8) -> u8 { a.saturating_sub(1) }` },
  { rule: "RUST-TYPE:5", name: "a function whose own name contains one is not one", expect: "silent",
    code: `pub fn my_saturating_sub(a: u8) -> u8 { a - 1 }` },
  { rule: "RUST-DEAD:1", name: "an allow that hides dead code", expect: "fires",
    code: `#[allow(dead_code)]\npub fn f() {}` },
  { rule: "RUST-DEAD:1", name: "an allow about something else is not one", expect: "silent",
    code: `#[allow(clippy::needless_return)]\npub fn f() {}` },
  { rule: "RUST-DEAD:2", name: "a comment", expect: "fires",
    code: `// this is a comment\npub fn f() {}` },
  { rule: "RUST-DEAD:2", name: "a comment inside a string is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { "// not a comment" }` },
  { rule: "RUST-DEAD:2", name: "a url in a string is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { "https://example.invalid/x" }` },
  { rule: "RUST-DEAD:2", name: "a raw string holding a comment is not a comment", expect: "silent",
    code: `pub fn f() -> &'static str { r#"// raw"# }` },
  { rule: "RUST-DEAD:3", name: "todo!", expect: "fires",
    code: `pub fn f() { todo!() }` },
  { rule: "RUST-DEAD:3", name: "todo as an identifier is not the macro", expect: "silent",
    code: `pub fn f() -> u8 { let todo = 1; todo }` },
  { rule: "RUST-DEAD:4", name: "a glob import", expect: "fires",
    code: `use std::collections::*;\npub fn f() {}` },
  { rule: "RUST-TRUTH:2", name: "reading the environment", expect: "fires",
    code: `pub fn f() -> Result<String, std::env::VarError> { std::env::var("HOME") }` },
  { rule: "RUST-LOG:1", name: "println outside the entry point", expect: "fires",
    code: `pub fn f() { println!("hello"); }` },
  { rule: "RUST-LOG:2", name: "taking the output handle", expect: "fires",
    code: `pub fn f() { let _ = std::io::stdout(); }` },
  { rule: "RUST-LOG:3", name: "control: a captured identifier in the message", expect: "fires",
    code: `pub fn f(id: u64) { tracing::info!("saved {id}"); }` },
  { rule: "RUST-LOG:3", name: "a positional argument is the same offence", expect: "fires",
    code: `pub fn f(id: u64) { tracing::info!("saved {}", id); }` },
  { rule: "RUST-LOG:3", name: "every level is judged, not only info", expect: "fires",
    code: `pub fn f(id: u64) { tracing::warn!("retrying {id}"); }` },
  { rule: "RUST-LOG:3", name: "a field beside a constant message is the shape that works", expect: "silent",
    code: `pub fn f(id: u64) { tracing::info!(order = %id, "saved"); }` },
  { rule: "RUST-LOG:3", name: "a message with nothing in it", expect: "silent",
    code: `pub fn f() { tracing::info!("saved"); }` },
  { rule: "RUST-LOG:3", name: "an escaped brace is a brace, not a value", expect: "silent",
    code: `pub fn f() { tracing::info!("a {{literal}} brace"); }` },
  { rule: "RUST-TESTS:1", name: "a test module under src", expect: "fires",
    code: `#[cfg(test)]\nmod tests {}` },
  { rule: "RUST-ERROR:1", name: "comparing against another type's None is not Option::None", expect: "silent",
    code: `pub enum Delimiter { None, Brace }\npub fn f(d: Delimiter) -> bool { matches!(d, Delimiter::None) }` },
  { rule: "RUST-ERROR:1", name: "comparing against Option::None is still caught", expect: "fires",
    code: `pub fn f(v: Option<u8>) -> bool { v == None }` },
  { rule: "RUST-ERROR:1", name: "the fallible family reached as a path, not a method", expect: "fires",
    code: `pub fn f(v: Option<u8>) -> u8 { let g = Option::unwrap; g(v) }` },
  { rule: "RUST-ERROR:3", name: "an Err arm answering with an empty string built the long way", expect: "fires",
    code: `pub fn f(v: Result<String, u8>) -> String { match v { Ok(s) => s, Err(e) => { let _ = e; "".to_string() } } }` },
  { rule: "RUST-DEAD:3", name: "a panic that says the work is not done", expect: "fires",
    code: `pub fn f() { panic!("not implemented yet") }` },
  { rule: "RUST-DEAD:3", name: "a panic that says something real is the crash door", expect: "silent",
    code: `pub fn f(n: u8) { if n == 0 { panic!("the config named no port") } }` },
  { rule: "RUST-TRUTH:2", name: "the environment reached through a subprocess", expect: "fires",
    code: `pub fn f() -> std::io::Result<std::process::Output> { std::process::Command::new("printenv").output() }` },
  { rule: "RUST-TRUTH:2", name: "running an ordinary program is not reading the environment", expect: "silent",
    code: `pub fn f() -> std::io::Result<std::process::Output> { std::process::Command::new("git").output() }` },
  { rule: "RUST-TRUTH:2", name: "the same read done at compile time", expect: "fires",
    code: `pub const HOME: &str = env!("HOME");` },
  { rule: "RUST-TRUTH:2", name: "a key cargo sets itself is still a setting under src", expect: "fires",
    code: `pub const HERE: &str = env!("CARGO_MANIFEST_DIR");` },
  { rule: "RUST-TRUTH:2", name: "and inside a macro argument under src", expect: "fires",
    code: `pub fn f() -> String { format!("{}", env!("CARGO_PKG_NAME")) }` },
  { rule: "RUST-ERROR:9", name: "a file that is not Rust at all", expect: "fires",
    code: `this is not rust {{{` },

  { rule: "RUST-TYPE:4", name: "a cast inside a macro argument", expect: "fires",
    code: `pub fn f(n: u32) { println!("{}", n as u8); }` },
  { rule: "RUST-TRUTH:2", name: "an environment read inside a macro argument", expect: "fires",
    code: `pub fn f() { println!("{:?}", std::env::var("HOME")); }` },
  { rule: "RUST-DEAD:3", name: "todo! inside a macro argument", expect: "fires",
    code: `pub fn f() { println!("{}", todo!()); }` },
  { rule: "RUST-LAYER:2", name: "a crate path inside a macro argument", expect: "fires",
    code: `pub fn f() { println!("{:?}", crate::f); }` },
  { rule: "RUST-LAYER:2", name: "a use statement is where a crate path belongs", expect: "silent",
    code: `use crate::f as g;\npub fn h() -> u8 { let _ = g; 1 }` },
  { rule: "RUST-TYPE:4", name: "a rename inside a macro body is not a cast", expect: "silent",
    code: `macro_rules! bring { () => { use std::collections::HashMap as Map; }; }\npub fn f() { bring!(); }` },

  { rule: "RUST-TYPE:4", name: "a float cast inside a macro argument is still a cast", expect: "fires",
    code: `pub fn f(n: u64) { println!("{}", n as f64); }` },
  { rule: "RUST-TYPE:4", name: "a query macro's column type override is not a numeric cast", expect: "silent",
    code: `pub fn f(role: &str) { let _ = sqlx::query!("insert $1", role as &str); }` },
  { rule: "RUST-TYPE:4", name: "an override to an Option type inside a macro is not a numeric cast", expect: "silent",
    code: `pub fn f(plan: Option<&str>) { let _ = sqlx::query!("insert $1", plan as Option<&str>); }` },
  { rule: "RUST-TYPE:4", name: "an override to a named type inside a macro is not a numeric cast", expect: "silent",
    code: `pub struct Role;\npub fn f(role: Role) { let _ = sqlx::query!("insert $1", role as Role); }` },
  { rule: "RUST-TYPE:4", name: "a pointer cast written as Rust, not as macro tokens, is still a cast", expect: "fires",
    code: `pub fn f(x: &u8) -> *const u8 { x as *const u8 }` },

  { rule: "RUST-TYPE:4", name: "a cast to an inferred type inside a macro hides its target and is still a cast", expect: "fires",
    code: `pub fn f(n: u64) { println!("{}", n as _); }` },
  { rule: "RUST-TYPE:4", name: "a pointer cast inside a macro argument is still a cast", expect: "fires",
    code: `pub fn f(x: &u8) { println!("{:?}", x as *const u8); }` },
];
